# [실습] 데이터프레임 탐색 (2)

1) pandas 라이브러리를 pd 별칭을 주어 불러오세요.

In [1]:
import pandas as pd

2) 다음 경로의 파일을 읽어 graduate 데이터프레임을 만드세요.

- 파일 경로: 'Graduate_apply.csv'
- 대소문자를 구분하니 주의하세요.

**[Graduate_apply 데이터 셋 정보]**

- admit: 입학 승인 여부(0: 불합격, 1: 합격)
- gre: 시험 성적
- gpa: 학점
- rank: 대학 순위

In [3]:
path = './../00_data/Graduate_apply.csv'

graduate = pd.read_csv(path)

3) 상위 10개 행을 확인하세요.

In [4]:
graduate.head(10)

   admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
4      0  520  2.93     4
5      1  760  3.00     2
6      1  560  2.98     1
7      0  400  3.08     2
8      1  540  3.39     3
9      0  700  3.92     2

4) 행과 열의 개수를 확인하세요.

In [5]:
graduate.shape

(400, 4)

5) 각 열의 값 개수와 데이터 형식등을 한 번에 확인하세요.

In [6]:
graduate.info

<bound method DataFrame.info of      admit  gre   gpa  rank
0        0  380  3.61     3
1        1  660  3.67     3
2        1  800  4.00     1
3        1  640  3.19     4
4        0  520  2.93     4
..     ...  ...   ...   ...
395      0  620  4.00     2
396      0  560  3.04     3
397      0  460  2.63     2
398      0  700  3.65     2
399      0  600  3.89     3

[400 rows x 4 columns]>

6) 기초통계정보를 확인하세요.

In [7]:
graduate.describe()

            admit         gre         gpa       rank
count  400.000000  400.000000  400.000000  400.00000
mean     0.317500  587.700000    3.389900    2.48500
std      0.466087  115.516536    0.380567    0.94446
min      0.000000  220.000000    2.260000    1.00000
25%      0.000000  520.000000    3.130000    2.00000
50%      0.000000  580.000000    3.395000    2.00000
75%      1.000000  660.000000    3.670000    3.00000
max      1.000000  800.000000    4.000000    4.00000

7) 범주형 값을 갖는 rank 열의 고유값과 그들의 개수를 확인하세요.

In [11]:
graduate['rank'].value_counts()

rank
2    151
3    121
4     67
1     61
Name: count, dtype: int64

8) gre, gpa 열의 평균값을 한 번에 확인하세요.

In [10]:

graduate.mean('gre','gpa')

C:\Users\playdata2\AppData\Local\Temp\ipykernel_9480\2266444292.py:1: Pandas4Warning: Starting with pandas version 4.0 all arguments of mean will be keyword-only.
  graduate.mean('gre','gpa')

ValueError: For argument "skipna" expected type bool, received type str.

9) gre 열을 기준으로 오름차순으로 정렬해 확인하세요.

10) 다음 요구사항에 따라 구문을 순서대로 작성하고 확인하세요.

- rank 열을 기준으로 오름차순, rank 열 값이 같으면 gpa 열을 기준으로 내림차순으로 정렬해 tmp 테이터프레임으로 선언하세요.
- tmp 데이터프레임 인덱스 초기화 하세요.(단, 기존 인덱스 제거)
- tmp 데이터프레임을 확인하세요.