# [실습 1] 서울 열린데이터 광장 Open API 활용
- https://data.seoul.go.kr/
- 서울시 공공자전거 실시간 대여정보

In [1]:
# 라이브러리 불러오기
import urllib.request
import json
import pandas as pd

## 1.1. 서울시 공공자전거 실시간 대여정보 1,000건 가져오기

- 서울특별시 공공자전거 실시간 대여정보를 가져와 **bike** 데이터프레임을 만듭니다.
- 데이터셋은 대여소별 실시간 자전거 대여가능 건수, 거치율, 대여소 위치정보를 제공합니다.
- 호출시 시스템 부하로 한번에 최대 **1,000건**를 초과할수 없습니다.
- 우선 1,000개 행만 조회하세요.

In [3]:
# 인증키와  URL 주소
# https://data.seoul.go.kr/dataList/OA-15493/A/1/datasetView.do
# uv add python-dotenv

from dotenv import load_dotenv
import os

load_dotenv()

key = os.getenv('bike_key')
res_type = 'json'
start = 1
end = 1000

url = f'http://openapi.seoul.go.kr:8088/{key}/{res_type}/bikeList/{start}/{end}'

print(url)

http://openapi.seoul.go.kr:8088/52795054456a657838324e4b62547a/json/bikeList/1/1000

In [3]:
response = urllib.request.urlopen(url)
json_str = response.read().decode('utf-8')

print(json_str)

{"rentBikeStatus":{"list_total_count":1000,"RESULT":{"CODE":"INFO-000","MESSAGE":"정상 처리되었습니다."},"row":[{"rackTotCnt":"15","stationName":"102. 망원역 1번출구 앞","parkingBikeTotCnt":"12","shared":"80","stationLatitude":"37.55564880","stationLongitude":"126.91062927","stationId":"ST-4"},{"rackTotCnt":"14","stationName":"103. 망원역 2번출구 앞","parkingBikeTotCnt":"21","shared":"150","stationLatitude":"37.55495071","stationLongitude":"126.91083527","stationId":"ST-5"},{"rackTotCnt":"13","stationName":"104. 합정역 1번출구 앞","parkingBikeTotCnt":"14","shared":"108","stationLatitude":"37.55073929","stationLongitude":"126.91508484","stationId":"ST-6"},{"rackTotCnt":"5","stationName":"105. 합정역 5번출구 앞","parkingBikeTotCnt":"3","shared":"60","stationLatitude":"37.55000687","stationLongitude":"126.91482544","stationId":"ST-7"},{"rackTotCnt":"12","stationName":"106. 합정역 7번출구 앞","parkingBikeTotCnt":"12","shared":"100","stationLatitude":"37.54864502","stationLongitude":"126.91282654","stationId":"ST-8"},{"rackTotCnt":"10","stationName":"107. 수협 연남동지점","parkingBikeTotCnt":"8","shared":"80","stationLatitude":"37.55784607","stationLongitude":"126.91871643","stationId":"ST-9"},{"rackTotCnt":"12","stationName":"108. 서교동 사거리","parkingBikeTotCnt":"19","shared":"158","stationLatitude":"37.55274582","stationLongitude":"126.91861725","stationId":"ST-10"},{"rackTotCnt":"10","stationName":"111. 상수역 2번출구 앞","parkingBikeTotCnt":"17","shared":"170","stationLatitude":"37.54787064","stationLongitude":"126.92353058","stationId":"ST-15"},{"rackTotCnt":"28","stationName":"113. 홍대입구역 2번출구 앞","parkingBikeTotCnt":"46","shared":"164","stationLatitude":"37.55743790","stationLongitude":"126.92382050","stationId":"ST-18"},{"rackTotCnt":"15","stationName":"114. 홍대입구역 8번출구 앞","parkingBikeTotCnt":"6","shared":"40","stationLatitude":"37.55706024","stationLongitude":"126.92442322","stationId":"ST-20"},{"rackTotCnt":"15","stationName":"115. 마스타 빌딩 앞","parkingBikeTotCnt":"20","shared":"133","stationLatitude":"37.55893326","stationLongitude":"126.92711639","stationId":"ST-12"},{"rackTotCnt":"23","stationName":"117. 홍은사거리","parkingBikeTotCnt":"0","shared":"0","stationLatitude":"37.59115982","stationLongitude":"126.94132996","stationId":"ST-17"},{"rackTotCnt":"9","stationName":"118. 광흥창역 2번출구 앞","parkingBikeTotCnt":"5","shared":"56","stationLatitude":"37.54773331","stationLongitude":"126.93176270","stationId":"ST-19"},{"rackTotCnt":"10","stationName":"119. 서강나루 공원","parkingBikeTotCnt":"19","shared":"190","stationLatitude":"37.54520798","stationLongitude":"126.93146515","stationId":"ST-21"},{"rackTotCnt":"5","stationName":"120. 신수동 사거리","parkingBikeTotCnt":"3","shared":"60","stationLatitude":"37.54524231","stationLongitude":"126.93411255","stationId":"ST-22"},{"rackTotCnt":"15","stationName":"121. 마포소방서 앞","parkingBikeTotCnt":"17","shared":"113","stationLatitude":"37.54976654","stationLongitude":"126.93317413","stationId":"ST-23"},{"rackTotCnt":"10","stationName":"122. 신성기사식당 앞","parkingBikeTotCnt":"12","shared":"120","stationLatitude":"37.54745865","stationLongitude":"126.93837738","stationId":"ST-24"},{"rackTotCnt":"20","stationName":"123. 문화촌 공원","parkingBikeTotCnt":"2","shared":"10","stationLatitude":"37.59432983","stationLongitude":"126.94738770","stationId":"ST-25"},{"rackTotCnt":"35","stationName":"124. 서강대 정문 건너편","parkingBikeTotCnt":"40","shared":"114","stationLatitude":"37.55113983","stationLongitude":"126.93698883","stationId":"ST-26"},{"rackTotCnt":"20","stationName":"126. 서강대 후문 옆","parkingBikeTotCnt":"18","shared":"90","stationLatitude":"37.55041122","stationLongitude":"126.94384766","stationId":"ST-28"},{"rackTotCnt":"9","stationName":"127. 현대벤처빌 앞","parkingBikeTotCnt":"11","shared":"122","stationLatitude":"37.55352020","stationLongitude":"126.93695068","stationId":"ST-29"},{"rackTotCnt":"19","stationName":"128. 신촌역(2호선) 1번출구 옆","parkingBikeTotCnt":"21","shared":"111","stationLatitude":"37.55549622","stationLongitude":"126.93634033","stationId":"ST-30"},{"rackTotCnt":"10","stationName":"129. 신촌역(2호선) 6번출구 옆","parkingBikeTotCnt":"20","shared":"200","stationLatitude":"37.55505371","stationLongitude":"126.93756866","stationId":"ST-31"},{"rackTotCnt":"10","stationName":"130. 신촌역(2호선) 7번출구 앞","parkingBikeTotCnt":"14","shared":"140","stationLatitude":"37.55504990","stationLongitude":"126.93626404","stationId":"ST-32"},{"rackTotCnt":"20","stationName":"131. 증산2교","parkingBikeTotCnt":"5","shared":"25","stationLatitude":"37.58417130","stationLongitude":"126.91110229","stationId":"ST-33"},{"rackTotCnt":"15","stationName":"133. 해담는다리","parkingBikeTotCnt":"2","shared":"13","stationLatitude":"37.58203125","stationLongitude":"126.90899658","stationId":"ST-35"},{"rackTotCnt":"8","stationName":"134. 연세로 명물길","parkingBikeTotCnt":"12","shared":"150","stationLatitude":"37.55789185","stationLongitude":"126.93807983","stationId":"ST-36"},{"rackTotCnt":"10","stationName":"135. 명물길 원형무대 앞","parkingBikeTotCnt":"8","shared":"80","stationLatitude":"37.55922699","stationLongitude":"126.93984222","stationId":"ST-37"},{"rackTotCnt":"10","stationName":"137. 신촌기차역입구 교차로","parkingBikeTotCnt":"15","shared":"150","stationLatitude":"37.55681229","stationLongitude":"126.94318390","stationId":"ST-39"},{"rackTotCnt":"10","stationName":"138. 신촌동 제1공영주차장 앞","parkingBikeTotCnt":"1","shared":"10","stationLatitude":"37.55917740","stationLongitude":"126.93452454","stationId":"ST-40"},{"rackTotCnt":"10","stationName":"139. 연세대 정문 건너편","parkingBikeTotCnt":"14","shared":"140","stationLatitude":"37.55986404","stationLongitude":"126.93441772","stationId":"ST-43"},{"rackTotCnt":"22","stationName":"140. 이화여대 후문","parkingBikeTotCnt":"14","shared":"64","stationLatitude":"37.56000900","stationLongitude":"126.94073486","stationId":"ST-41"},{"rackTotCnt":"10","stationName":"141. 연대 대운동장 옆","parkingBikeTotCnt":"14","shared":"140","stationLatitude":"37.56238174","stationLongitude":"126.93264771","stationId":"ST-42"},{"rackTotCnt":"11","stationName":"142. 아현역 4번출구 앞","parkingBikeTotCnt":"13","shared":"118","stationLatitude":"37.55720139","stationLongitude":"126.95566559","stationId":"ST-200"},{"rackTotCnt":"8","stationName":"143. 공덕역 2번출구","parkingBikeTotCnt":"7","shared":"88","stationLatitude":"37.54464722","stationLongitude":"126.95008850","stationId":"ST-201"},{"rackTotCnt":"9","stationName":"145. 공덕역 5번출구","parkingBikeTotCnt":"7","shared":"78","stationLatitude":"37.54425049","stationLongitude":"126.95163727","stationId":"ST-203"},{"rackTotCnt":"12","stationName":"146. 마포역 2번출구 뒤","parkingBikeTotCnt":"12","shared":"100","stationLatitude":"37.53993607","stationLongitude":"126.94582367","stationId":"ST-204"},{"rackTotCnt":"5","stationName":"147. 마포역 4번출구 뒤","parkingBikeTotCnt":"8","shared":"160","stationLatitude":"37.53927231","stationLongitude":"126.94591522","stationId":"ST-205"},{"rackTotCnt":"11","stationName":"148. 용강동 주민센터 앞","parkingBikeTotCnt":"2","shared":"18","stationLatitude":"37.54234695","stationLongitude":"126.94302368","stationId":"ST-206"},{"rackTotCnt":"15","stationName":"150. 서강대역 2번출구 앞","parkingBikeTotCnt":"20","shared":"133","stationLatitude":"37.55295563","stationLongitude":"126.93434143","stationId":"ST-207"},{"rackTotCnt":"10","stationName":"153. 성산2교 사거리","parkingBikeTotCnt":"9","shared":"90","stationLatitude":"37.56469727","stationLongitude":"126.91261292","stationId":"ST-210"},{"rackTotCnt":"11","stationName":"154. 마포구청역 ","parkingBikeTotCnt":"1","shared":"9","stationLatitude":"37.56090927","stationLongitude":"126.90549469","stationId":"ST-211"},{"rackTotCnt":"15","stationName":"155. 가좌역1 번출구 앞","parkingBikeTotCnt":"8","shared":"53","stationLatitude":"37.56829453","stationLongitude":"126.91504669","stationId":"ST-212"},{"rackTotCnt":"10","stationName":"156. 서울서부지방법원 앞","parkingBikeTotCnt":"1","shared":"10","stationLatitude":"37.54933167","stationLongitude":"126.95491791","stationId":"ST-213"},{"rackTotCnt":"12","stationName":"157. 애오개역 4번출구 앞","parkingBikeTotCnt":"0","shared":"0","stationLatitude":"37.55300140","stationLongitude":"126.95668793","stationId":"ST-214"},{"rackTotCnt":"5","stationName":"159. 이대역 4번 출구","parkingBikeTotCnt":"21","shared":"420","stationLatitude":"37.55695343","stationLongitude":"126.94634247","stationId":"ST-216"},{"rackTotCnt":"13","stationName":"160. 북아현동 가구거리","parkingBikeTotCnt":"13","shared":"100","stationLatitude":"37.55754852","stationLongitude":"126.95938110","stationId":"ST-217"},{"rackTotCnt":"8","stationName":"161. 무악재역1번 출구","parkingBikeTotCnt":"1","shared":"13","stationLatitude":"37.58224487","stationLongitude":"126.95064545","stationId":"ST-218"},{"rackTotCnt":"15","stationName":"162. 봉원고가차도 밑","parkingBikeTotCnt":"59","shared":"393","stationLatitude":"37.56626129","stationLongitude":"126.94667053","stationId":"ST-219"},{"rackTotCnt":"6","stationName":"163. 명지전문대학교 정문 앞","parkingBikeTotCnt":"6","shared":"100","stationLatitude":"37.58369827","stationLongitude":"126.92496490","stationId":"ST-220"},{"rackTotCnt":"10","stationName":"164. 북가좌1동 주민센터 ","parkingBikeTotCnt":"21","shared":"210","stationLatitude":"37.57447815","stationLongitude":"126.91004944","stationId":"ST-221"},{"rackTotCnt":"20","stationName":"165. 중앙근린공원","parkingBikeTotCnt":"15","shared":"75","stationLatitude":"37.57513809","stationLongitude":"126.91394043","stationId":"ST-222"},{"rackTotCnt":"20","stationName":"166. 가재울 초등학교","parkingBikeTotCnt":"13","shared":"65","stationLatitude":"37.57381821","stationLongitude":"126.91923523","stationId":"ST-223"},{"rackTotCnt":"15","stationName":"167. 연가초등학교 옆","parkingBikeTotCnt":"14","shared":"93","stationLatitude":"37.57946014","stationLongitude":"126.91712952","stationId":"ST-224"},{"rackTotCnt":"10","stationName":"169. 북가좌 삼거리","parkingBikeTotCnt":"10","shared":"100","stationLatitude":"37.57300186","stationLongitude":"126.90779877","stationId":"ST-226"},{"rackTotCnt":"10","stationName":"170. DMC파크뷰자이아파트 302동 앞","parkingBikeTotCnt":"5","shared":"50","stationLatitude":"37.57311249","stationLongitude":"126.92244720","stationId":"ST-227"},{"rackTotCnt":"10","stationName":"171. 임광빌딩 앞","parkingBikeTotCnt":"3","shared":"30","stationLatitude":"37.56472397","stationLongitude":"126.96727753","stationId":"ST-228"},{"rackTotCnt":"8","stationName":"173. 서대문역 8번출구 앞","parkingBikeTotCnt":"7","shared":"88","stationLatitude":"37.56477737","stationLongitude":"126.96614838","stationId":"ST-230"},{"rackTotCnt":"15","stationName":"175. 홍연2교옆","parkingBikeTotCnt":"3","shared":"20","stationLatitude":"37.57806778","stationLongitude":"126.93088531","stationId":"ST-231"},{"rackTotCnt":"10","stationName":"176. 명지대학교 도서관","parkingBikeTotCnt":"9","shared":"90","stationLatitude":"37.58109665","stationLongitude":"126.92402649","stationId":"ST-555"},{"rackTotCnt":"8","stationName":"177. 북가좌 초등학교","parkingBikeTotCnt":"13","shared":"163","stationLatitude":"37.57763672","stationLongitude":"126.90965271","stationId":"ST-345"},{"rackTotCnt":"9","stationName":"178. 증산3교 앞","parkingBikeTotCnt":"4","shared":"44","stationLatitude":"37.57987595","stationLongitude":"126.90634918","stationId":"ST-349"},{"rackTotCnt":"14","stationName":"179. 가좌역 4번출구 앞","parkingBikeTotCnt":"18","shared":"129","stationLatitude":"37.56877518","stationLongitude":"126.91529846","stationId":"ST-232"},{"rackTotCnt":"10","stationName":"180. 충정로역 7번출구 아래","parkingBikeTotCnt":"4","shared":"40","stationLatitude":"37.55996704","stationLongitude":"126.96246338","stationId":"ST-233"},{"rackTotCnt":"15","stationName":"181. 망원초록길 입구","parkingBikeTotCnt":"10","shared":"67","stationLatitude":"37.55134201","stationLongitude":"126.90267181","stationId":"ST-339"},{"rackTotCnt":"15","stationName":"183. 하늘채코오롱아파트 건너편","parkingBikeTotCnt":"15","shared":"100","stationLatitude":"37.56538773","stationLongitude":"126.91932678","stationId":"ST-341"},{"rackTotCnt":"8","stationName":"184.망원우체국사거리 인근","parkingBikeTotCnt":"9","shared":"113","stationLatitude":"37.55894852","stationLongitude":"126.90775299","stationId":"ST-342"},{"rackTotCnt":"15","stationName":"185. 마포 신수공원 앞","parkingBikeTotCnt":"0","shared":"0","stationLatitude":"37.54254532","stationLongitude":"126.93429565","stationId":"ST-343"},{"rackTotCnt":"40","stationName":"186. 월드컵공원","parkingBikeTotCnt":"58","shared":"145","stationLatitude":"37.56396484","stationLongitude":"126.89820862","stationId":"ST-344"},{"rackTotCnt":"9","stationName":"188. 홍은동 정원여중 입구","parkingBikeTotCnt":"13","shared":"144","stationLatitude":"37.58638763","stationLongitude":"126.93512726","stationId":"ST-346"},{"rackTotCnt":"10","stationName":"191. 서우빌딩","parkingBikeTotCnt":"8","shared":"80","stationLatitude":"37.57889175","stationLongitude":"126.91073608","stationId":"ST-347"},{"rackTotCnt":"8","stationName":"192. 연서어린이공원","parkingBikeTotCnt":"7","shared":"88","stationLatitude":"37.57222748","stationLongitude":"126.92306519","stationId":"ST-348"},{"rackTotCnt":"10","stationName":"194. 증산교 앞","parkingBikeTotCnt":"13","shared":"130","stationLatitude":"37.57731628","stationLongitude":"126.90296936","stationId":"ST-350"},{"rackTotCnt":"10","stationName":"195. 모래내고가차도 ","parkingBikeTotCnt":"15","shared":"150","stationLatitude":"37.56765747","stationLongitude":"126.91780853","stationId":"ST-351"},{"rackTotCnt":"10","stationName":"198. 충정2교","parkingBikeTotCnt":"6","shared":"60","stationLatitude":"37.56390762","stationLongitude":"126.96497345","stationId":"ST-354"},{"rackTotCnt":"30","stationName":"199. 서울 월드컵 경기장","parkingBikeTotCnt":"44","shared":"147","stationLatitude":"37.56684494","stationLongitude":"126.89644623","stationId":"ST-443"},{"rackTotCnt":"22","stationName":"200. 국회의원회관","parkingBikeTotCnt":"8","shared":"36","stationLatitude":"37.52841568","stationLongitude":"126.91391754","stationId":"ST-45"},{"rackTotCnt":"15","stationName":"201. 진미파라곤 앞","parkingBikeTotCnt":"5","shared":"33","stationLatitude":"37.53123856","stationLongitude":"126.92133331","stationId":"ST-46"},{"rackTotCnt":"30","stationName":"202. 국민일보 앞","parkingBikeTotCnt":"21","shared":"70","stationLatitude":"37.52881622","stationLongitude":"126.92453003","stationId":"ST-47"},{"rackTotCnt":"15","stationName":"203. 국회의사당역 3번출구 옆","parkingBikeTotCnt":"26","shared":"173","stationLatitude":"37.52805710","stationLongitude":"126.91870117","stationId":"ST-51"},{"rackTotCnt":"13","stationName":"204. 국회의사당역 5번출구 옆","parkingBikeTotCnt":"16","shared":"123","stationLatitude":"37.52816391","stationLongitude":"126.91702271","stationId":"ST-50"},{"rackTotCnt":"20","stationName":"205. 산업은행 앞","parkingBikeTotCnt":"20","shared":"100","stationLatitude":"37.52626419","stationLongitude":"126.92050934","stationId":"ST-52"},{"rackTotCnt":"35","stationName":"206. KBS 앞","parkingBikeTotCnt":"53","shared":"151","stationLatitude":"37.52466583","stationLongitude":"126.91802216","stationId":"ST-53"},{"rackTotCnt":"46","stationName":"207. 여의나루역 1번출구 앞","parkingBikeTotCnt":"0","shared":"0","stationLatitude":"37.52715683","stationLongitude":"126.93190002","stationId":"ST-73"},{"rackTotCnt":"22","stationName":"209. 유진투자증권빌딩 앞","parkingBikeTotCnt":"64","shared":"291","stationLatitude":"37.52461243","stationLongitude":"126.92783356","stationId":"ST-55"},{"rackTotCnt":"10","stationName":"212. 여의도역 1번출구 옆","parkingBikeTotCnt":"0","shared":"0","stationLatitude":"37.52136230","stationLongitude":"126.92346191","stationId":"ST-58"},{"rackTotCnt":"19","stationName":"213. KT앞","parkingBikeTotCnt":"22","shared":"116","stationLatitude":"37.52190781","stationLongitude":"126.91895294","stationId":"ST-59"},{"rackTotCnt":"21","stationName":"214. 금융감독원 앞","parkingBikeTotCnt":"32","shared":"152","stationLatitude":"37.52302170","stationLongitude":"126.92083740","stationId":"ST-60"},{"rackTotCnt":"15","stationName":"217. NH농협은행 앞","parkingBikeTotCnt":"55","shared":"367","stationLatitude":"37.52207947","stationLongitude":"126.93036652","stationId":"ST-66"},{"rackTotCnt":"12","stationName":"219. 롯데캐슬엠파이어 옆","parkingBikeTotCnt":"11","shared":"92","stationLatitude":"37.52069473","stationLongitude":"126.92583466","stationId":"ST-62"},{"rackTotCnt":"30","stationName":"220. 미성아파트 A동 앞","parkingBikeTotCnt":"15","shared":"50","stationLatitude":"37.51936340","stationLongitude":"126.92604828","stationId":"ST-63"},{"rackTotCnt":"10","stationName":"221. 여의도초교 앞","parkingBikeTotCnt":"0","shared":"0","stationLatitude":"37.52267456","stationLongitude":"126.93778992","stationId":"ST-67"},{"rackTotCnt":"12","stationName":"222. 시범아파트버스정류장 옆","parkingBikeTotCnt":"25","shared":"208","stationLatitude":"37.51902008","stationLongitude":"126.93688965","stationId":"ST-68"},{"rackTotCnt":"20","stationName":"223. 진주아파트상가 앞","parkingBikeTotCnt":"27","shared":"135","stationLatitude":"37.51913071","stationLongitude":"126.93337250","stationId":"ST-69"},{"rackTotCnt":"20","stationName":"224. 롯데캐슬 앞","parkingBikeTotCnt":"13","shared":"65","stationLatitude":"37.52008820","stationLongitude":"126.93236542","stationId":"ST-70"},{"rackTotCnt":"26","stationName":"225. 앙카라공원 앞","parkingBikeTotCnt":"15","shared":"58","stationLatitude":"37.51758575","stationLongitude":"126.92961884","stationId":"ST-71"},{"rackTotCnt":"19","stationName":"226. 샛강역 1번출구 앞","parkingBikeTotCnt":"27","shared":"142","stationLatitude":"37.51776505","stationLongitude":"126.92841339","stationId":"ST-72"},{"rackTotCnt":"20","stationName":"227. 양평1나들목 보행통로 입구","parkingBikeTotCnt":"22","shared":"110","stationLatitude":"37.54466629","stationLongitude":"126.88835907","stationId":"ST-277"},{"rackTotCnt":"10","stationName":"228. 선유도역 3번출구 앞","parkingBikeTotCnt":"20","shared":"200","stationLatitude":"37.53845978","stationLongitude":"126.89450836","stationId":"ST-278"},{"rackTotCnt":"25","stationName":"229. 양평1 보행육교 앞","parkingBikeTotCnt":"54","shared":"216","stationLatitude":"37.53587341","stationLongitude":"126.89218140","stationId":"ST-279"},{"rackTotCnt":"13","stationName":"230. 영등포구청역 7번출구","parkingBikeTotCnt":"4","shared":"31","stationLatitude":"37.52435684","stationLongitude":"126.89600372","stationId":"ST-413"},{"rackTotCnt":"10","stationName":"231. 남부고용노동지청 남측","parkingBikeTotCnt":"7","shared":"70","stationLatitude":"37.52450562","stationLongitude":"126.89182281","stationId":"ST-280"},{"rackTotCnt":"20","stationName":"232. 양평우림 이비즈센타 앞","parkingBikeTotCnt":"18","shared":"90","stationLatitude":"37.52565002","stationLongitude":"126.88781738","stationId":"ST-281"},{"rackTotCnt":"10","stationName":"233. 양평1동 YP센터 앞","parkingBikeTotCnt":"29","shared":"290","stationLatitude":"37.52848816","stationLongitude":"126.89164734","stationId":"ST-282"},{"rackTotCnt":"10","stationName":"236. 문래동자이아파트 앞","parkingBikeTotCnt":"14","shared":"140","stationLatitude":"37.51615524","stationLongitude":"126.89461517","stationId":"ST-285"},{"rackTotCnt":"20","stationName":"237. 보라매 두산위브 건너편","parkingBikeTotCnt":"13","shared":"65","stationLatitude":"37.49652100","stationLongitude":"126.91492462","stationId":"ST-286"},{"rackTotCnt":"17","stationName":"238. 제2구민체육센타 앞","parkingBikeTotCnt":"19","shared":"112","stationLatitude":"37.52638626","stationLongitude":"126.90275574","stationId":"ST-287"},{"rackTotCnt":"19","stationName":"239. 유스호스텔 앞","parkingBikeTotCnt":"32","shared":"168","stationLatitude":"37.52585220","stationLongitude":"126.90328217","stationId":"ST-288"},{"rackTotCnt":"10","stationName":"240. 문래역 4번출구 앞","parkingBikeTotCnt":"20","shared":"200","stationLatitude":"37.51873779","stationLongitude":"126.89557648","stationId":"ST-289"},{"rackTotCnt":"10","stationName":"241. 신길우성1차아파트 앞 공원","parkingBikeTotCnt":"4","shared":"40","stationLatitude":"37.50501633","stationLongitude":"126.89853668","stationId":"ST-290"},{"rackTotCnt":"15","stationName":"242. 신길선원가와인아파트 앞","parkingBikeTotCnt":"6","shared":"40","stationLatitude":"37.51093292","stationLongitude":"126.91022491","stationId":"ST-291"},{"rackTotCnt":"15","stationName":"243. 이앤씨드림타워 앞","parkingBikeTotCnt":"35","shared":"233","stationLatitude":"37.52708435","stationLongitude":"126.89138031","stationId":"ST-292"},{"rackTotCnt":"20","stationName":"244. 영등포삼환아파트 앞","parkingBikeTotCnt":"53","shared":"265","stationLatitude":"37.53007889","st

**데이터셋 정보**

- rackTotCnt: 거치대개수
- stationName: 대여소이름
- parkingBikeTotCnt: 자전거주차총건수
- shared: 거치율
- stationLatitude: 위도
- stationLongitude: 경도
- stationId: 대여소ID

## 1.2. 서울시 공공자전거 실시간 대여정보 모든 데이터 가져오기

- 위 실습 결과로 작성된 구문을 수정하여 모든 데이터를 가져와 **bike** 데이터프레임을 다시 만듭니다.
- while 문을 사용해 JSON 문자열을 연결 한 후 이후 과정을 진행합니다.

In [4]:
start = 1
end = 1000
result = []
while True:

  url = f'http://openapi.seoul.go.kr:8088/{key}/{res_type}/bikeList/{start}/{end}'
  response = urllib.request.urlopen(url)
  json_str = response.read().decode('utf-8')
  # print(json_str)
  json_object = json.loads(json_str)
  # bike = pd.json_normalize(json_object['rentBikeStatus']['row'])
  # result.append(bike)
  result.extend(json_object['rentBikeStatus']['row'])

  print(len(json_object['rentBikeStatus']['row']))

  # print(json_object['rentBikeStatus']['list_total_count'])
  if int(json_object['rentBikeStatus']['list_total_count']) < 1000:
    break

  start += 1000
  end += 1000
final = pd.json_normalize(result)
print(len(result))
print(final.info())

1000
1000
727
2727
<class 'pandas.DataFrame'>
RangeIndex: 2727 entries, 0 to 2726
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rackTotCnt         2727 non-null   str
 1   stationName        2727 non-null   str
 2   parkingBikeTotCnt  2727 non-null   str
 3   shared             2727 non-null   str
 4   stationLatitude    2727 non-null   str
 5   stationLongitude   2727 non-null   str
 6   stationId          2727 non-null   str
dtypes: str(7)
memory usage: 149.3 KB
None

In [5]:
loop = 0
result = []

while True:
  start = 1 + 1000 * loop # 1 1001 2001 ~
  end = 1000 + 1000 * loop # 1000 2000 3000

  url = f'http://openapi.seoul.go.kr:8088/{key}/{res_type}/bikeList/{start}/{end}'

  # 데이터 가져오기
  response = urllib.request.urlopen(url)
  json_str = response.read().decode('utf-8')

  # 딕셔너리로 변환
  json_object = json.loads(json_str)

  result += json_object['rentBikeStatus']['row']

  print(loop)

  print(len(result))
  print('=' * 40)
  if (len(result) % 1000 != 0):
    break
  loop += 1

0
1000
========================================
1
2000
========================================
2
2727
========================================

- 하위 데이터를 확인합니다.

In [ ]:
# json_object = json.loads(json_str)
# print(json_object)

# # result = json_object['rentBikeStatus']['row']

# # 데이터 플레임으로 변환
# bike = pd.json_normalize(json_object['rentBikeStatus']['row'])
# bike

{'rentBikeStatus': {'list_total_count': 727, 'RESULT': {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다.'}, 'row': [{'rackTotCnt': '10', 'stationName': '3912. 삼호아파트 앞', 'parkingBikeTotCnt': '8', 'shared': '80', 'stationLatitude': '37.49385834', 'stationLongitude': '126.85646820', 'stationId': 'ST-2855'}, {'rackTotCnt': '10', 'stationName': '3914. 신도림쌍용플래티넘노블아파트 앞', 'parkingBikeTotCnt': '17', 'shared': '170', 'stationLatitude': '37.50126266', 'stationLongitude': '126.89118195', 'stationId': 'ST-2892'}, {'rackTotCnt': '10', 'stationName': '3915. 동선아파트 앞', 'parkingBikeTotCnt': '14', 'shared': '140', 'stationLatitude': '37.49382782', 'stationLongitude': '126.83907318', 'stationId': 'ST-2949'}, {'rackTotCnt': '10', 'stationName': '3918. 이좋은집오피스텔 앞', 'parkingBikeTotCnt': '11', 'shared': '110', 'stationLatitude': '37.49499130', 'stationLongitude': '126.84185028', 'stationId': 'ST-2997'}, {'rackTotCnt': '14', 'stationName': '3919. 구로역·NC신구로점 버스정류장(구로역 방면)', 'parkingBikeTotCnt': '16', 'shared': '114', 'stationLatitude': '37.50096512', 'stationLongitude': '126.88237000', 'stationId': 'ST-3013'}, {'rackTotCnt': '10', 'stationName': '3920. 개봉역2번출구 B', 'parkingBikeTotCnt': '2', 'shared': '20', 'stationLatitude': '37.49555206', 'stationLongitude': '126.85697937', 'stationId': 'ST-3055'}, {'rackTotCnt': '16', 'stationName': '3922. 서울남부교정시설 앞', 'parkingBikeTotCnt': '18', 'shared': '113', 'stationLatitude': '37.47715378', 'stationLongitude': '126.83985901', 'stationId': 'ST-3067'}, {'rackTotCnt': '10', 'stationName': '3923. 구로공구상가 앞', 'parkingBikeTotCnt': '4', 'shared': '40', 'stationLatitude': '37.50075531', 'stationLongitude': '126.87708282', 'stationId': 'ST-3088'}, {'rackTotCnt': '10', 'stationName': '3924. 오류동 계림웨스트밸리 앞', 'parkingBikeTotCnt': '13', 'shared': '130', 'stationLatitude': '37.49090958', 'stationLongitude': '126.82965088', 'stationId': 'ST-3103'}, {'rackTotCnt': '10', 'stationName': '3925. 중앙유통단지 앞 B', 'parkingBikeTotCnt': '61', 'shared': '610', 'stationLatitude': '37.50127029', 'stationLongitude': '126.87678528', 'stationId': 'ST-3124'}, {'rackTotCnt': '9', 'stationName': '3927. 구로월드아파트 앞', 'parkingBikeTotCnt': '37', 'shared': '411', 'stationLatitude': '37.50519562', 'stationLongitude': '126.87619019', 'stationId': 'ST-3182'}, {'rackTotCnt': '10', 'stationName': '3928.고척아이파크아파트 106동 앞', 'parkingBikeTotCnt': '15', 'shared': '150', 'stationLatitude': '37.49801254', 'stationLongitude': '126.86098480', 'stationId': 'ST-3195'}, {'rackTotCnt': '15', 'stationName': '3929. 고척아이파크아파트 205동 앞', 'parkingBikeTotCnt': '16', 'shared': '107', 'stationLatitude': '37.50108719', 'stationLongitude': '126.86045837', 'stationId': 'ST-3194'}, {'rackTotCnt': '8', 'stationName': '3930. 온수역 2번 출구 앞', 'parkingBikeTotCnt': '16', 'shared': '200', 'stationLatitude': '37.49179459', 'stationLongitude': '126.82500458', 'stationId': 'ST-3189'}, {'rackTotCnt': '7', 'stationName': '3931. 천왕역 3번 출구 뒤', 'parkingBikeTotCnt': '35', 'shared': '500', 'stationLatitude': '37.48690414', 'stationLongitude': '126.83894348', 'stationId': 'ST-3223'}, {'rackTotCnt': '10', 'stationName': '3932. 개봉센트레빌레우스아파트 앞', 'parkingBikeTotCnt': '6', 'shared': '60', 'stationLatitude': '37.49752045', 'stationLongitude': '126.85295105', 'stationId': 'ST-3222'}, {'rackTotCnt': '10', 'stationName': '3933. 오류동부골든아파트 후문 옆', 'parkingBikeTotCnt': '19', 'shared': '190', 'stationLatitude': '37.49938202', 'stationLongitude': '126.84114075', 'stationId': 'ST-3237'}, {'rackTotCnt': '7', 'stationName': '3934. 철도교통관제센터 정문 앞', 'parkingBikeTotCnt': '11', 'shared': '157', 'stationLatitude': '37.49708176', 'stationLongitude': '126.87788391', 'stationId': 'ST-3225'}, {'rackTotCnt': '10', 'stationName': '3935. 고대구로병원 앞', 'parkingBikeTotCnt': '17', 'shared': '170', 'stationLatitude': '37.49312592', 'stationLongitude': '126.88424683', 'stationId': 'ST-3252'}, {'rackTotCnt': '10', 'stationName': '3936. 힐스테이트 신도림역', 'parkingBikeTotCnt': '5', 'shared': '50', 'stationLatitude': '37.50683594', 'stationLongitude': '126.88478851', 'stationId': 'ST-3303'}, {'rackTotCnt': '10', 'stationName': '3937. 개봉역 신영지웰에스테이트', 'parkingBikeTotCnt': '4', 'shared': '40', 'stationLatitude': '37.49563599', 'stationLongitude': '126.85797882', 'stationId': 'ST-3306'}, {'rackTotCnt': '15', 'stationName': '3939.신도림역 3번출구', 'parkingBikeTotCnt': '86', 'shared': '573', 'stationLatitude': '37.50760651', 'stationLongitude': '126.89134979', 'stationId': 'ST-3311'}, {'rackTotCnt': '10', 'stationName': '3956. 대륭테크노타운21차 앞', 'parkingBikeTotCnt': '16', 'shared': '160', 'stationLatitude': '37.46557617', 'stationLongitude': '126.88724518', 'stationId': 'ST-2637'}, {'rackTotCnt': '10', 'stationName': '3958. 롯데캐슬2차 마을버스 정류장(18804) 뒤편', 'parkingBikeTotCnt': '5', 'shared': '50', 'stationLatitude': '37.45739746', 'stationLongitude': '126.89341736', 'stationId': 'ST-2638'}, {'rackTotCnt': '10', 'stationName': '3959. 시흥사거리(시흥동 994-3 앞)', 'parkingBikeTotCnt': '13', 'shared': '130', 'stationLatitude': '37.45415115', 'stationLongitude': '126.90045166', 'stationId': 'ST-2639'}, {'rackTotCnt': '10', 'stationName': '3963. 에이스 하드웨어(시흥대로 396) 앞', 'parkingBikeTotCnt': '9', 'shared': '90', 'stationLatitude': '37.46865845', 'stationLongitude': '126.89826202', 'stationId': 'ST-2641'}, {'rackTotCnt': '8', 'stationName': '3966. 독산역1번출구 B', 'parkingBikeTotCnt': '11', 'shared': '138', 'stationLatitude': '37.46709442', 'stationLongitude': '126.88920593', 'stationId': 'ST-2642'}, {'rackTotCnt': '16', 'stationName': '3967. 혜명양로원 담장 옆(2)', 'parkingBikeTotCnt': '25', 'shared': '156', 'stationLatitude': '37.45191956', 'stationLongitude': '126.91375732', 'stationId': 'ST-2893'}, {'rackTotCnt': '20', 'stationName': '3969. 독산역 롯데캐슬 104동 앞', 'parkingBikeTotCnt': '22', 'shared': '110', 'stationLatitude': '37.46237564', 'stationLongitude': '126.89179230', 'stationId': 'ST-2895'}, {'rackTotCnt': '6', 'stationName': '3970. 시흥4동주민센터 앞', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.45894241', 'stationLongitude': '126.90592957', 'stationId': 'ST-2910'}, {'rackTotCnt': '5', 'stationName': '3971. 순흥안씨묘 건너편', 'parkingBikeTotCnt': '3', 'shared': '60', 'stationLatitude': '37.45838165', 'stationLongitude': '126.90807343', 'stationId': 'ST-2911'}, {'rackTotCnt': '7', 'stationName': '3973. 독산2동주민센터 앞', 'parkingBikeTotCnt': '16', 'shared': '229', 'stationLatitude': '37.46322250', 'stationLongitude': '126.90357208', 'stationId': 'ST-2913'}, {'rackTotCnt': '10', 'stationName': '3974.  안천중학교', 'parkingBikeTotCnt': '5', 'shared': '50', 'stationLatitude': '37.45936584', 'stationLongitude': '126.88677979', 'stationId': 'ST-2931'}, {'rackTotCnt': '10', 'stationName': '3975.현대시티아울렛 가산', 'parkingBikeTotCnt': '9', 'shared': '90', 'stationLatitude': '37.47739792', 'stationLongitude': '126.88877869', 'stationId': 'ST-3029'}, {'rackTotCnt': '5', 'stationName': '3980. 금천현대홈타운 후문 서부샛길', 'parkingBikeTotCnt': '2', 'shared': '40', 'stationLatitude': '37.46139526', 'stationLongitude': '126.89003754', 'stationId': 'ST-3032'}, {'rackTotCnt': '10', 'stationName': '3983. 금천구청역 1번 출구', 'parkingBikeTotCnt': '21', 'shared': '210', 'stationLatitude': '37.45703506', 'stationLongitude': '126.89432526', 'stationId': 'ST-2932'}, {'rackTotCnt': '5', 'stationName': '3984. 가산롯데아이티캐슬', 'parkingBikeTotCnt': '18', 'shared': '360', 'stationLatitude': '37.47636795', 'stationLongitude': '126.88083649', 'stationId': 'ST-2999'}, {'rackTotCnt': '20', 'stationName': '3985. 디폴리스 지식산업센터', 'parkingBikeTotCnt': '24', 'shared': '120', 'stationLatitude': '37.48017502', 'stationLongitude': '126.87680054', 'stationId': 'ST-2964'}, {'rackTotCnt': '5', 'stationName': '3986.청년주택 독산동점', 'parkingBikeTotCnt': '7', 'shared': '140', 'stationLatitude': '37.46754074', 'stationLongitude': '126.89282227', 'stationId': 'ST-3196'}, {'rackTotCnt': '10', 'stationName': '3987. LG전자가산A와 가산테라타워 사이', 'parkingBikeTotCnt': '13', 'shared': '130', 'stationLatitude': '37.47520447', 'stationLongitude': '126.89012909', 'stationId': 'ST-3219'}, {'rackTotCnt': '5', 'stationName': '3988. 엘아르베뉴 102동 앞', 'parkingBikeTotCnt': '11', 'shared': '220', 'stationLatitude': '37.47452545', 'stationLongitude': '126.88707733', 'stationId': 'ST-3236'}, {'rackTotCnt': '10', 'stationName': '3989.가산디지털단지역 9번출구 앞', 'parkingBikeTotCnt': '1', 'shared': '10', 'stationLatitude': '37.48055267', 'stationLongitude': '126.88175964', 'stationId': 'ST-3396'}, {'rackTotCnt': '10', 'stationName': '4002. 상계주공 14단지 상가 앞', 'parkingBikeTotCnt': '16', 'shared': '160', 'stationLatitude': '37.66963577', 'stationLongitude': '127.05942535', 'stationId': 'ST-2698'}, {'rackTotCnt': '10', 'stationName': '4004. 당고개입구오거리 당현천변', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.66260529', 'stationLongitude': '127.07557678', 'stationId': 'ST-2700'}, {'rackTotCnt': '10', 'stationName': '4005. 중계2차 한화꿈에그린 101동 인근', 'parkingBikeTotCnt': '1', 'shared': '10', 'stationLatitude': '37.65955734', 'stationLongitude': '127.07525635', 'stationId': 'ST-2701'}, {'rackTotCnt': '9', 'stationName': '4007. 노원 을지대학교 병원', 'parkingBikeTotCnt': '14', 'shared': '156', 'stationLatitude': '37.63666916', 'stationLongitude': '127.06969452', 'stationId': 'ST-2702'}, {'rackTotCnt': '10', 'stationName': '4008. 하계 어린이 공원', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.63341522', 'stationLongitude': '127.06916046', 'stationId': 'ST-2703'}, {'rackTotCnt': '20', 'stationName': '4009. 월계프라자', 'parkingBikeTotCnt': '17', 'shared': '85', 'stationLatitude': '37.63284302', 'stationLongitude': '127.05213165', 'stationId': 'ST-2704'}, {'rackTotCnt': '10', 'stationName': '4011. 월계 센트럴 아이파크', 'parkingBikeTotCnt': '20', 'shared': '200', 'stationLatitude': '37.62917328', 'stationLongitude': '127.05693054', 'stationId': 'ST-2705'}, {'rackTotCnt': '11', 'stationName': '4013. 중계 롯데마트', 'parkingBikeTotCnt': '3', 'shared': '27', 'stationLatitude': '37.64559555', 'stationLongitude': '127.07135773', 'stationId': 'ST-2706'}, {'rackTotCnt': '10', 'stationName': '4014. 불암산역 3번 출구', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.67030334', 'stationLongitude': '127.07884216', 'stationId': 'ST-2707'}, {'rackTotCnt': '9', 'stationName': '4016. 노원 마들스타디움', 'parkingBikeTotCnt': '8', 'shared': '89', 'stationLatitude': '37.64509583', 'stationLongitude': '127.05855560', 'stationId': 'ST-2754'}, {'rackTotCnt': '20', 'stationName': '4017. 월계 청백1단지 아파트 정류장', 'parkingBikeTotCnt': '22', 'shared': '110', 'stationLatitude': '37.63459396', 'stationLongitude': '127.05206299', 'stationId': 'ST-2708'}, {'rackTotCnt': '8', 'stationName': '4018. 상계주공15단지 버스정류소', 'parkingBikeTotCnt': '1', 'shared': '13', 'stationLatitude': '37.66782761', 'stationLongitude': '127.05683899', 'stationId': 'ST-2709'}, {'rackTotCnt': '7', 'stationName': '4019. 상계주공10단지 버스정류소', 'parkingBikeTotCnt': '2', 'shared': '29', 'stationLatitude': '37.66214371', 'stationLongitude': '127.05819702', 'stationId': 'ST-2710'}, {'rackTotCnt': '10', 'stationName': '4020. 중계동 성모빌딩 앞 ', 'parkingBikeTotCnt': '3', 'shared': '30', 'stationLatitude': '37.65116119', 'stationLongitude': '127.07659149', 'stationId': 'ST-2711'}, {'rackTotCnt': '10', 'stationName': '4021. 중계본동 입구', 'parkingBikeTotCnt': '1', 'shared': '10', 'stationLatitude': '37.64426041', 'stationLongitude': '127.08331299', 'stationId': 'ST-2712'}, {'rackTotCnt': '20', 'stationName': '4023. 월계역 1번 출구', 'parkingBikeTotCnt': '30', 'shared': '150', 'stationLatitude': '37.63441086', 'stationLongitude': '127.05886841', 'stationId': 'ST-2713'}, {'rackTotCnt': '10', 'stationName': '4024. 꿈의숲 SK뷰 아파트', 'parkingBikeTotCnt': '14', 'shared': '140', 'stationLatitude': '37.62045288', 'stationLongitude': '127.05445099', 'stationId': 'ST-2714'}, {'rackTotCnt': '10', 'stationName': '4025. 한천교 동편', 'parkingBikeTotCnt': '17', 'shared': '170', 'stationLatitude': '37.62533569', 'stationLongitude': '127.07019043', 'stationId': 'ST-2715'}, {'rackTotCnt': '10', 'stationName': '4026. 상계주공1단지아파트', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.64795303', 'stationLongitude': '127.05793762', 'stationId': 'ST-2716'}, {'rackTotCnt': '10', 'stationName': '4027. 한내 행복발전소 옆', 'parkingBikeTotCnt': '9', 'shared': '90', 'stationLatitude': '37.62741089', 'stationLongitude': '127.06214142', 'stationId': 'ST-2791'}, {'rackTotCnt': '10', 'stationName': '4028. 한일유앤아이아파트 105동 인근', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.65351868', 'stationLongitude': '127.07130432', 'stationId': 'ST-2717'}, {'rackTotCnt': '10', 'stationName': '4031. 청암예술학교 앞', 'parkingBikeTotCnt': '2', 'shared': '20', 'stationLatitude': '37.65153503', 'stationLongitude': '127.07327271', 'stationId': 'ST-2729'}, {'rackTotCnt': '10', 'stationName': '4032. 불암주유소 앞', 'parkingBikeTotCnt': '5', 'shared': '50', 'stationLatitude': '37.65149689', 'stationLongitude': '127.07704163', 'stationId': 'ST-2719'}, {'rackTotCnt': '9', 'stationName': '4033. 녹천역 4번 출구 옆', 'parkingBikeTotCnt': '20', 'shared': '222', 'stationLatitude': '37.64292908', 'stationLongitude': '127.05194855', 'stationId': 'ST-2720'}, {'rackTotCnt': '6', 'stationName': '4035. 휴플러스 수락한신아파트 101동 앞', 'parkingBikeTotCnt': '1', 'shared': '17', 'stationLatitude': '37.67436600', 'stationLongitude': '127.05947113', 'stationId': 'ST-2804'}, {'rackTotCnt': '9', 'stationName': '4036. 하계역 6번출구', 'parkingBikeTotCnt': '23', 'shared': '256', 'stationLatitude': '37.63793945', 'stationLongitude': '127.06715393', 'stationId': 'ST-2792'}, {'rackTotCnt': '15', 'stationName': '4037. 물넘이교', 'parkingBikeTotCnt': '1', 'shared': '7', 'stationLatitude': '37.65408325', 'stationLongitude': '127.07195282', 'stationId': 'ST-2835'}, {'rackTotCnt': '10', 'stationName': '4039. 서울시 북부여성발전센터', 'parkingBikeTotCnt': '6', 'shared': '60', 'stationLatitude': '37.64304352', 'stationLongitude': '127.06213379', 'stationId': 'ST-2859'}, {'rackTotCnt': '10', 'stationName': '4040. 공릉로 26길', 'parkingBikeTotCnt': '2', 'shared': '20', 'stationLatitude': '37.61965561', 'stationLongitude': '127.08146667', 'stationId': 'ST-2861'}, {'rackTotCnt': '8', 'stationName': '4041. 공릉역3번출구', 'parkingBikeTotCnt': '15', 'shared': '188', 'stationLatitude': '37.62527466', 'stationLongitude': '127.07288361', 'stationId': 'ST-2896'}, {'rackTotCnt': '10', 'stationName': '4042. 상계문화정보도서관', 'parkingBikeTotCnt': '17', 'shared': '170', 'stationLatitude': '37.67851257', 'stationLongitude': '127.05174255', 'stationId': 'ST-2914'}, {'rackTotCnt': '10', 'stationName': '4043. 상계주공13단지 1301동', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.66674042', 'stationLongitude': '127.06388855', 'stationId': 'ST-2954'}, {'rackTotCnt': '4', 'stationName': '4044. 공릉산 백세문 입구', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.62813568', 'stationLongitude': '127.08625793', 'stationId': 'ST-2955'}, {'rackTotCnt': '10', 'stationName': '4054. 창동한신아파트 버스정류소', 'parkingBikeTotCnt': '21', 'shared': '210', 'stationLatitude': '37.64601898', 'stationLongitude': '127.03527069', 'stationId': 'ST-2722'}, {'rackTotCnt': '15', 'stationName': '4058. 다락원체육공원 전망대 입구', 'parkingBikeTotCnt': '5', 'shared': '33', 'stationLatitude': '37.69101334', 'stationLongitude': '127.04916382', 'stationId': 'ST-2723'}, {'rackTotCnt': '9', 'stationName': '4062. 평화도봉공원 주변', 'parkingBikeTotCnt': '12', 'shared': '133', 'stationLatitude': '37.66252136', 'stationLongitude': '127.04270935', 'stationId': 'ST-2724'}, {'rackTotCnt': '10', 'stationName': '4064. 신창아파트 입구 앞', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.64051056', 'stationLongitude': '127.04082489', 'stationId': 'ST-2725'}, {'rackTotCnt': '10', 'stationName': '4073.방아골종합사회복지관', 'parkingBikeTotCnt': '19', 'shared': '190', 'stationLatitude': '37.66927338', 'stationLongitude': '127.03243256', 'stationId': 'ST-2730'}, {'rackTotCnt': '10', 'stationName': '4074. 도봉구육아종합지원센터(창동)', 'parkingBikeTotCnt': '7', 'shared': '70', 'stationLatitude': '37.63342667', 'stationLongitude': '127.04116058', 'stationId': 'ST-2727'}, {'rackTotCnt': '8', 'stationName': '4078. 원당공원 앞', 'parkingBikeTotCnt': '14', 'shared': '175', 'stationLatitude': '37.65854645', 'stationLongitude': '127.02767944', 'stationId': 'ST-2849'}, {'rackTotCnt': '4', 'stationName': '4080. 창동주공19단지앞 ', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.65242004', 'stationLongitude': '127.05229187', 'stationId': 'ST-2967'}, {'rackTotCnt': '8', 'stationName': '4083.도봉아이나라도서관 앞', 'parkingBikeTotCnt': '8', 'shared': '100', 'stationLatitude': '37.65898895', 'stationLongitude': '127.04973602', 'stationId': 'ST-3026'}, {'rackTotCnt': '10', 'stationName': '4084. 도봉동실내스포츠센터', 'parkingBikeTotCnt': '16', 'shared': '160', 'stationLatitude': '37.68125534', 'stationLongitude': '127.05047607', 'stationId': 'ST-3050'}, {'rackTotCnt': '10', 'stationName': '4086. 도봉로 534', 'parkingBikeTotCnt': '3', 'shared': '30', 'stationLatitude': '37.65295410', 'stationLongitude': '127.03754425', 'stationId': 'ST-3091'}, {'rackTotCnt': '10', 'stationName': '4087. 우이교 교차로', 'parkingBikeTotCnt': '20', 'shared': '200', 'stationLatitude': '37.64324570', 'stationLongitude': '127.03160095', 'stationId': 'ST-3092'}, {'rackTotCnt': '15', 'stationName': '4088. 김근태도서관', 'parkingBikeTotCnt': '11', 'shared': '73', 'stationLatitude': '37.68750763', 'stationLongitude': '127.04263306', 'stationId': 'ST-3093'}, {'rackTotCnt': '10', 'stationName': '4089. 동부센트레빌 앞', 'parkingBikeTotCnt': '8', 'shared': '80', 'stationLatitude': '37.66299057', 'stationLongitude': '127.03864288', 'stationId': 'ST-3119'}, {'rackTotCnt': '15', 'stationName': '4090. 녹천교 앞 사거리', 'parkingBikeTotCnt': '7', 'shared': '47', 'stationLatitude': '37.64564514', 'stationLongitude': '127.05459595', 'stationId': 'ST-3175'}, {'rackTotCnt': '15', 'stationName': '4091. 방학역2번출구', 'parkingBikeTotCnt': '19', 'shared': '127', 'stationLatitude': '37.66922379', 'stationLongitude': '127.04441833', 'stationId': 'ST-3172'}, {'rackTotCnt': '10', 'stationName': '4092. 도봉경찰서 교차로', 'parkingBikeTotCnt': '16', 'shared': '160', 'stationLatitude': '37.65265656', 'stationLongitude': '127.05309296', 'stationId': 'ST-3177'}, {'rackTotCnt': '6', 'stationName': '4094.도봉여성센터', 'parkingBikeTotCnt': '10', 'shared': '167', 'stationLatitude': '37.66334915', 'stationLongitude': '127.03045654', 'stationId': 'ST-3197'}, {'rackTotCnt': '8', 'stationName': '4095. 방학브라운스톤아파트', 'parkingBikeTotCnt': '22', 'shared': '275', 'stationLatitude': '37.66289139', 'stationLongitude': '127.04540253', 'stationId': 'ST-3269'}, {'rackTotCnt': '8', 'stationName': '4096.창동역2번출구 하나은행365 앞', 'parkingBikeTotCnt': '22', 'shared': '275', 'stationLatitude': '37.65283585', 'stationLongitude': '127.04550171', 'stationId': 'ST-3368'}, {'rackTotCnt': '8', 'stationName': '4097.숭미파출소 사거리', 'parkingBikeTotCnt': '2', 'shared': '25', 'stationLatitude': '37.64747620', 'stationLongitude': '127.02608490', 'stationId': 'ST-3399'}, {'rackTotCnt': '7', 'stationName': '4102. 휘경1동주민센터 앞', 'parkingBikeTotCnt': '4', 'shared': '57', 'stationLatitude': '37.59286499', 'stationLongitude': '127.06555939', 'stationId': 'ST-2496'}, {'rackTotCnt': '10', 'stationName': '4103. 휘경sk뷰아파트 앞', 'parkingBikeTotCnt': '8', 'shared': '80', 'stationLatitude': '37.59383774', 'stationLongitude': '127.06781769', 'stationId': 'ST-2497'}, {'rackTotCnt': '10', 'stationName': '4104. 외대앞역 교차로', 'parkingBikeTotCnt': '7', 'shared': '70', 'stationLatitude': '37.59436417', 'stationLongitude': '127.06459808', 'stationId': 'ST-2498'}, {'rackTotCnt': '10', 'stationName': '4105. 서울교통공사사거리 교통섬', 'parkingBikeTotCnt': '8', 'shared': '80', 'stationLatitude': '37.56324005', 'stationLongitude': '127.05799103', 'stationId': 'ST-2499'}, {'rackTotCnt': '10', 'stationName': '4107. 장안동근린공원 입구', 'parkingBikeTotCnt': '15', 'shared': '150', 'stationLatitude': '37.57677078', 'stationLongitude': '127.07189178', 'stationId': 'ST-2500'}, {'rackTotCnt': '25', 'stationName': '4108. 답십리파크자이아파트 앞', 'parkingBikeTotCnt': '18', 'shared': '72', 'stationLatitude': '37.56769180', 'stationLongitude': '127.05789185', 'stationId': 'ST-2501'}, {'rackTotCnt': '10', 'stationName': '41

,rackTotCnt,stationName,parkingBikeTotCnt,shared,stationLatitude,stationLongitude,stationId
0,10,3912. 삼호아파트 앞,8,80,37.49385834,126.85646820,ST-2855
1,10,3914. 신도림쌍용플래티넘노블아파트 앞,17,170,37.50126266,126.89118195,ST-2892
2,10,3915. 동선아파트 앞,14,140,37.49382782,126.83907318,ST-2949
3,10,3918. 이좋은집오피스텔 앞,11,110,37.49499130,126.84185028,ST-2997
4,14,3919. 구로역·NC신구로점 버스정류장(구로역 방면),16,114,37.50096512,126.88237000,ST-3013
...,...,...,...,...,...,...,...
722,8,6185.가양나들목,12,150,37.57341003,126.84345245,ST-3418
723,12,6187.마곡119안전센터 맞은편,4,33,37.55534744,126.82072449,ST-3415
724,10,6188.금호아파트,13,130,37.55619049,126.86463928,ST-3419
725,11,6189.데시앙플렉스 지식산업센터,13,118,37.56448364,126.84830475,ST-3424
726,10,6190.마곡광장(마곡나루역 5번출구),11,110,37.56614685,126.82738495,ST-3421

## 1.3. 실시간 대여정보 분석

### 1.3.1.데이터 탐색 및 전처리

- 열 이름, 데이터 형식 등 열 정보를 확인합니다.

In [5]:
final.info()

<class 'pandas.DataFrame'>
RangeIndex: 2727 entries, 0 to 2726
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rackTotCnt         2727 non-null   str
 1   stationName        2727 non-null   str
 2   parkingBikeTotCnt  2727 non-null   str
 3   shared             2727 non-null   str
 4   stationLatitude    2727 non-null   str
 5   stationLongitude   2727 non-null   str
 6   stationId          2727 non-null   str
dtypes: str(7)
memory usage: 149.3 KB

- 데이터 형식을 int로 변환합니다.
- 대상 열: rackTotCnt, parkingBikeTotCnt, shared
- 구문 예) df['Money'].astype('int')

In [6]:
# 분석을 위해 승하차 인원 컬럼을 숫자형으로 변환
final[['rackTotCnt', 'parkingBikeTotCnt', 'shared']] = final[['rackTotCnt', 'parkingBikeTotCnt', 'shared']].astype(int)

- 결과를 확인합니다.

In [7]:

final.head()

,rackTotCnt,stationName,parkingBikeTotCnt,shared,stationLatitude,stationLongitude,stationId
0,15,102. 망원역 1번출구 앞,12,80,37.55564880,126.91062927,ST-4
1,14,103. 망원역 2번출구 앞,21,150,37.55495071,126.91083527,ST-5
2,13,104. 합정역 1번출구 앞,14,108,37.55073929,126.91508484,ST-6
3,5,105. 합정역 5번출구 앞,3,60,37.55000687,126.91482544,ST-7
4,12,106. 합정역 7번출구 앞,13,108,37.54864502,126.91282654,ST-8

- 기초통계정보를 확인합니다.

In [8]:
final.describe()

        rackTotCnt  parkingBikeTotCnt      shared
count  2727.000000        2727.000000  2727.00000
mean     12.047305          12.114778   105.69747
std       5.600705          11.529144   100.31257
min       2.000000           0.000000     0.00000
25%      10.000000           4.000000    38.00000
50%      10.000000           9.000000    83.00000
75%      15.000000          17.000000   150.00000
max      65.000000         108.000000  1550.00000

### 1.3.2. 가장 많이 거치된 곳 TOP 10

- 자전거가 가장 많이 거치된 곳을 확인하기 위해 parkingBikeTotCnt 열로 내림차순 정렬한 후 상위 10개 행만 출력하세요.

In [9]:
bike_guchi_top10 = final.sort_values(by='parkingBikeTotCnt',ascending=False).head(10)
bike_guchi_top10

,rackTotCnt,stationName,parkingBikeTotCnt,shared,stationLatitude,stationLongitude,stationId
1647,62,2717.LG유플러스 마곡사옥,108,174,37.56133652,126.83390045,ST-2033
646,20,1009. 천호역4번출구(현대백화점),100,500,37.53866577,127.12424469,ST-493
2588,57,5096. LG사이언스파크 E14동,95,167,37.56349564,126.83583069,ST-3251
795,30,1210. 롯데월드타워(잠실역2번출구 쪽),86,287,37.51312637,127.10095978,ST-891
2021,15,3939.신도림역 3번출구,85,567,37.50760651,126.89134979,ST-3311
2257,10,4452. 삼성SDS,73,730,37.51633835,127.09985352,ST-2571
1910,20,3691. 둔촌역 2번출구,72,360,37.52710342,127.13651276,ST-2928
2638,30,5515.한강버스 망원 선착장,69,230,37.55466461,126.89590454,ST-3388
854,30,1291. 서울체육고등학교 앞,69,230,37.52193832,127.13186646,ST-1580
2685,20,5878. 우리은행 앞,69,345,37.52349091,126.92162323,ST-3315

### 1.3.3. 거치대 수가 가장 많은 곳 TOP 10

- 거치대 수가 가장 많은 곳을 확인하기 위해 rackTotCnt 열로 내림차순 정렬한 후 상위 10개 행만 출력하세요.

In [10]:
bike_rack_top10 = final.sort_values(by='rackTotCnt',ascending=False).head(10)
bike_rack_top10

,rackTotCnt,stationName,parkingBikeTotCnt,shared,stationLatitude,stationLongitude,stationId
1656,65,2728.마곡나루역 3번 출구,25,38,37.56580353,126.82807922,ST-2045
1647,62,2717.LG유플러스 마곡사옥,108,174,37.56133652,126.83390045,ST-2033
2588,57,5096. LG사이언스파크 E14동,95,167,37.56349564,126.83583069,ST-3251
274,51,450. 효자동 삼거리,15,29,37.58360291,126.97254944,ST-978
780,51,1193. 마곡센트럴타워 1차,28,55,37.55947113,126.83207703,ST-1688
83,46,207. 여의나루역 1번출구 앞,0,0,37.52715683,126.93190002,ST-73
1625,41,2652.송파 레미니스1단지 102동 앞,0,0,37.50883102,127.13426208,ST-1873
2584,40,5089. LG사이언스파크 E10동,45,113,37.56364822,126.83454132,ST-3128
534,40,829. 한강대교 북단 교차로,21,53,37.52293015,126.96169281,ST-1326
2591,40,5099. LG사이언스파크 E7동,41,103,37.56153488,126.83193970,ST-3260

### 1.3.4. 지도 시각화

- 위도와 경도 정보가 있으므로 지도상에 거치대 위치를 표시할 수 있습니다.
- 지도 시각화를 위해 folium 라이브러리를 설치합니다.

In [13]:
# 라이브러리 설치
# %pip install folium

- 위 분석에서 거치대가 가장 많은 곳의 좌표를 지도상에 표시합니다.

In [ ]:
import folium

m = folium.Map(location=[37.56580353, 126.82807922], tiles='OpenStreetMap', zoom_start=17)

# 마커 표시
mark1 = folium.Marker([37.56580353, 126.82807922],
                      popup='LG유플러스 마곡 사옥',
                      icon=folium.Icon(color='red')
                      )

mark1.add_to(m)

m

In [13]:
import folium

# 1. 데이터프레임의 첫 번째 행(index 0)에서 위도, 경도 추출
# 'stationLatitude'와 'stationLongitude'는 데이터프레임의 컬럼명과 일치해야 합니다.
start_lat = bike_rack_top10.iloc[0]['stationLatitude']
start_lng = bike_rack_top10.iloc[0]['stationLongitude']




m = folium.Map(location=[start_lat, start_lng], tiles='OpenStreetMap', zoom_start=17)

# 마커 표시
mark1 = folium.Marker([start_lat, start_lng],
                      popup='LG유플러스 마곡 사옥',
                      icon=folium.Icon(color='red')
                      )

mark1.add_to(m)

m

In [12]:
bike_rack_top10 = final.sort_values(by='rackTotCnt',ascending=False).head(10)
bike_rack_top10

,rackTotCnt,stationName,parkingBikeTotCnt,shared,stationLatitude,stationLongitude,stationId
1656,65,2728.마곡나루역 3번 출구,25,38,37.56580353,126.82807922,ST-2045
1647,62,2717.LG유플러스 마곡사옥,108,174,37.56133652,126.83390045,ST-2033
2588,57,5096. LG사이언스파크 E14동,95,167,37.56349564,126.83583069,ST-3251
274,51,450. 효자동 삼거리,15,29,37.58360291,126.97254944,ST-978
780,51,1193. 마곡센트럴타워 1차,28,55,37.55947113,126.83207703,ST-1688
83,46,207. 여의나루역 1번출구 앞,0,0,37.52715683,126.93190002,ST-73
1625,41,2652.송파 레미니스1단지 102동 앞,0,0,37.50883102,127.13426208,ST-1873
2584,40,5089. LG사이언스파크 E10동,45,113,37.56364822,126.83454132,ST-3128
534,40,829. 한강대교 북단 교차로,21,53,37.52293015,126.96169281,ST-1326
2591,40,5099. LG사이언스파크 E7동,41,103,37.56153488,126.83193970,ST-3260