# [실습 1] 서울 열린데이터 광장 Open API 활용
- https://data.seoul.go.kr/
- 서울시 공공자전거 실시간 대여정보

In [1]:
# 라이브러리 불러오기
import urllib.request
import json
import pandas as pd

## 1.1. 서울시 공공자전거 실시간 대여정보 1,000건 가져오기

- 서울특별시 공공자전거 실시간 대여정보를 가져와 **bike** 데이터프레임을 만듭니다.
- 데이터셋은 대여소별 실시간 자전거 대여가능 건수, 거치율, 대여소 위치정보를 제공합니다.
- 호출시 시스템 부하로 한번에 최대 **1,000건**를 초과할수 없습니다.
- 우선 1,000개 행만 조회하세요.

In [9]:
# 인증키와  URL 주소
# https://data.seoul.go.kr/dataList/OA-15493/A/1/datasetView.do
# uv add python-dotenv

from dotenv import load_dotenv
import os

load_dotenv()

key = os.getenv('bike_key')
res_type = 'json'
start = 1
end = 1000

url = f'http://openapi.seoul.go.kr:8088/{key}/{res_type}/bikeList/{start}/{end}'

print(url)

http://openapi.seoul.go.kr:8088/52795054456a657838324e4b62547a/json/bikeList/1/1000

In [10]:
response = urllib.request.urlopen(url)
json_str = response.read().decode('utf-8')

print(json_str)

{"rentBikeStatus":{"list_total_count":1000,"RESULT":{"CODE":"INFO-000","MESSAGE":"정상 처리되었습니다."},"row":[{"rackTotCnt":"15","stationName":"102. 망원역 1번출구 앞","parkingBikeTotCnt":"29","shared":"193","stationLatitude":"37.55564880","stationLongitude":"126.91062927","stationId":"ST-4"},{"rackTotCnt":"14","stationName":"103. 망원역 2번출구 앞","parkingBikeTotCnt":"16","shared":"114","stationLatitude":"37.55495071","stationLongitude":"126.91083527","stationId":"ST-5"},{"rackTotCnt":"13","stationName":"104. 합정역 1번출구 앞","parkingBikeTotCnt":"17","shared":"131","stationLatitude":"37.55073929","stationLongitude":"126.91508484","stationId":"ST-6"},{"rackTotCnt":"5","stationName":"105. 합정역 5번출구 앞","parkingBikeTotCnt":"2","shared":"40","stationLatitude":"37.55000687","stationLongitude":"126.91482544","stationId":"ST-7"},{"rackTotCnt":"12","stationName":"106. 합정역 7번출구 앞","parkingBikeTotCnt":"15","shared":"125","stationLatitude":"37.54864502","stationLongitude":"126.91282654","stationId":"ST-8"},{"rackTotCnt":"10","stationName":"107. 수협 연남동지점","parkingBikeTotCnt":"9","shared":"90","stationLatitude":"37.55784607","stationLongitude":"126.91871643","stationId":"ST-9"},{"rackTotCnt":"12","stationName":"108. 서교동 사거리","parkingBikeTotCnt":"18","shared":"150","stationLatitude":"37.55274582","stationLongitude":"126.91861725","stationId":"ST-10"},{"rackTotCnt":"10","stationName":"111. 상수역 2번출구 앞","parkingBikeTotCnt":"15","shared":"150","stationLatitude":"37.54787064","stationLongitude":"126.92353058","stationId":"ST-15"},{"rackTotCnt":"28","stationName":"113. 홍대입구역 2번출구 앞","parkingBikeTotCnt":"51","shared":"182","stationLatitude":"37.55743790","stationLongitude":"126.92382050","stationId":"ST-18"},{"rackTotCnt":"15","stationName":"114. 홍대입구역 8번출구 앞","parkingBikeTotCnt":"5","shared":"33","stationLatitude":"37.55706024","stationLongitude":"126.92442322","stationId":"ST-20"},{"rackTotCnt":"15","stationName":"115. 마스타 빌딩 앞","parkingBikeTotCnt":"23","shared":"153","stationLatitude":"37.55893326","stationLongitude":"126.92711639","stationId":"ST-12"},{"rackTotCnt":"23","stationName":"117. 홍은사거리","parkingBikeTotCnt":"3","shared":"13","stationLatitude":"37.59115982","stationLongitude":"126.94132996","stationId":"ST-17"},{"rackTotCnt":"9","stationName":"118. 광흥창역 2번출구 앞","parkingBikeTotCnt":"7","shared":"78","stationLatitude":"37.54773331","stationLongitude":"126.93176270","stationId":"ST-19"},{"rackTotCnt":"10","stationName":"119. 서강나루 공원","parkingBikeTotCnt":"21","shared":"210","stationLatitude":"37.54520798","stationLongitude":"126.93146515","stationId":"ST-21"},{"rackTotCnt":"5","stationName":"120. 신수동 사거리","parkingBikeTotCnt":"4","shared":"80","stationLatitude":"37.54524231","stationLongitude":"126.93411255","stationId":"ST-22"},{"rackTotCnt":"15","stationName":"121. 마포소방서 앞","parkingBikeTotCnt":"19","shared":"127","stationLatitude":"37.54976654","stationLongitude":"126.93317413","stationId":"ST-23"},{"rackTotCnt":"10","stationName":"122. 신성기사식당 앞","parkingBikeTotCnt":"11","shared":"110","stationLatitude":"37.54745865","stationLongitude":"126.93837738","stationId":"ST-24"},{"rackTotCnt":"20","stationName":"123. 문화촌 공원","parkingBikeTotCnt":"1","shared":"5","stationLatitude":"37.59432983","stationLongitude":"126.94738770","stationId":"ST-25"},{"rackTotCnt":"35","stationName":"124. 서강대 정문 건너편","parkingBikeTotCnt":"41","shared":"117","stationLatitude":"37.55113983","stationLongitude":"126.93698883","stationId":"ST-26"},{"rackTotCnt":"20","stationName":"126. 서강대 후문 옆","parkingBikeTotCnt":"22","shared":"110","stationLatitude":"37.55041122","stationLongitude":"126.94384766","stationId":"ST-28"},{"rackTotCnt":"9","stationName":"127. 현대벤처빌 앞","parkingBikeTotCnt":"12","shared":"133","stationLatitude":"37.55352020","stationLongitude":"126.93695068","stationId":"ST-29"},{"rackTotCnt":"19","stationName":"128. 신촌역(2호선) 1번출구 옆","parkingBikeTotCnt":"16","shared":"84","stationLatitude":"37.55549622","stationLongitude":"126.93634033","stationId":"ST-30"},{"rackTotCnt":"10","stationName":"129. 신촌역(2호선) 6번출구 옆","parkingBikeTotCnt":"18","shared":"180","stationLatitude":"37.55505371","stationLongitude":"126.93756866","stationId":"ST-31"},{"rackTotCnt":"10","stationName":"130. 신촌역(2호선) 7번출구 앞","parkingBikeTotCnt":"13","shared":"130","stationLatitude":"37.55504990","stationLongitude":"126.93626404","stationId":"ST-32"},{"rackTotCnt":"20","stationName":"131. 증산2교","parkingBikeTotCnt":"10","shared":"50","stationLatitude":"37.58417130","stationLongitude":"126.91110229","stationId":"ST-33"},{"rackTotCnt":"15","stationName":"133. 해담는다리","parkingBikeTotCnt":"5","shared":"33","stationLatitude":"37.58203125","stationLongitude":"126.90899658","stationId":"ST-35"},{"rackTotCnt":"8","stationName":"134. 연세로 명물길","parkingBikeTotCnt":"11","shared":"138","stationLatitude":"37.55789185","stationLongitude":"126.93807983","stationId":"ST-36"},{"rackTotCnt":"10","stationName":"135. 명물길 원형무대 앞","parkingBikeTotCnt":"22","shared":"220","stationLatitude":"37.55922699","stationLongitude":"126.93984222","stationId":"ST-37"},{"rackTotCnt":"10","stationName":"137. 신촌기차역입구 교차로","parkingBikeTotCnt":"4","shared":"40","stationLatitude":"37.55681229","stationLongitude":"126.94318390","stationId":"ST-39"},{"rackTotCnt":"10","stationName":"138. 신촌동 제1공영주차장 앞","parkingBikeTotCnt":"1","shared":"10","stationLatitude":"37.55917740","stationLongitude":"126.93452454","stationId":"ST-40"},{"rackTotCnt":"10","stationName":"139. 연세대 정문 건너편","parkingBikeTotCnt":"15","shared":"150","stationLatitude":"37.55986404","stationLongitude":"126.93441772","stationId":"ST-43"},{"rackTotCnt":"22","stationName":"140. 이화여대 후문","parkingBikeTotCnt":"13","shared":"59","stationLatitude":"37.56000900","stationLongitude":"126.94073486","stationId":"ST-41"},{"rackTotCnt":"10","stationName":"141. 연대 대운동장 옆","parkingBikeTotCnt":"13","shared":"130","stationLatitude":"37.56238174","stationLongitude":"126.93264771","stationId":"ST-42"},{"rackTotCnt":"11","stationName":"142. 아현역 4번출구 앞","parkingBikeTotCnt":"14","shared":"127","stationLatitude":"37.55720139","stationLongitude":"126.95566559","stationId":"ST-200"},{"rackTotCnt":"8","stationName":"143. 공덕역 2번출구","parkingBikeTotCnt":"10","shared":"125","stationLatitude":"37.54464722","stationLongitude":"126.95008850","stationId":"ST-201"},{"rackTotCnt":"9","stationName":"145. 공덕역 5번출구","parkingBikeTotCnt":"15","shared":"167","stationLatitude":"37.54425049","stationLongitude":"126.95163727","stationId":"ST-203"},{"rackTotCnt":"12","stationName":"146. 마포역 2번출구 뒤","parkingBikeTotCnt":"11","shared":"92","stationLatitude":"37.53993607","stationLongitude":"126.94582367","stationId":"ST-204"},{"rackTotCnt":"5","stationName":"147. 마포역 4번출구 뒤","parkingBikeTotCnt":"10","shared":"200","stationLatitude":"37.53927231","stationLongitude":"126.94591522","stationId":"ST-205"},{"rackTotCnt":"11","stationName":"148. 용강동 주민센터 앞","parkingBikeTotCnt":"1","shared":"9","stationLatitude":"37.54234695","stationLongitude":"126.94302368","stationId":"ST-206"},{"rackTotCnt":"15","stationName":"150. 서강대역 2번출구 앞","parkingBikeTotCnt":"19","shared":"127","stationLatitude":"37.55295563","stationLongitude":"126.93434143","stationId":"ST-207"},{"rackTotCnt":"10","stationName":"153. 성산2교 사거리","parkingBikeTotCnt":"14","shared":"140","stationLatitude":"37.56469727","stationLongitude":"126.91261292","stationId":"ST-210"},{"rackTotCnt":"11","stationName":"154. 마포구청역 ","parkingBikeTotCnt":"7","shared":"64","stationLatitude":"37.56090927","stationLongitude":"126.90549469","stationId":"ST-211"},{"rackTotCnt":"15","stationName":"155. 가좌역1 번출구 앞","parkingBikeTotCnt":"6","shared":"40","stationLatitude":"37.56829453","stationLongitude":"126.91504669","stationId":"ST-212"},{"rackTotCnt":"10","stationName":"156. 서울서부지방법원 앞","parkingBikeTotCnt":"14","shared":"140","stationLatitude":"37.54933167","stationLongitude":"126.95491791","stationId":"ST-213"},{"rackTotCnt":"12","stationName":"157. 애오개역 4번출구 앞","parkingBikeTotCnt":"4","shared":"33","stationLatitude":"37.55300140","stationLongitude":"126.95668793","stationId":"ST-214"},{"rackTotCnt":"5","stationName":"159. 이대역 4번 출구","parkingBikeTotCnt":"6","shared":"120","stationLatitude":"37.55695343","stationLongitude":"126.94634247","stationId":"ST-216"},{"rackTotCnt":"13","stationName":"160. 북아현동 가구거리","parkingBikeTotCnt":"12","shared":"92","stationLatitude":"37.55754852","stationLongitude":"126.95938110","stationId":"ST-217"},{"rackTotCnt":"8","stationName":"161. 무악재역1번 출구","parkingBikeTotCnt":"1","shared":"13","stationLatitude":"37.58224487","stationLongitude":"126.95064545","stationId":"ST-218"},{"rackTotCnt":"15","stationName":"162. 봉원고가차도 밑","parkingBikeTotCnt":"61","shared":"407","stationLatitude":"37.56626129","stationLongitude":"126.94667053","stationId":"ST-219"},{"rackTotCnt":"6","stationName":"163. 명지전문대학교 정문 앞","parkingBikeTotCnt":"5","shared":"83","stationLatitude":"37.58369827","stationLongitude":"126.92496490","stationId":"ST-220"},{"rackTotCnt":"10","stationName":"164. 북가좌1동 주민센터 ","parkingBikeTotCnt":"5","shared":"50","stationLatitude":"37.57447815","stationLongitude":"126.91004944","stationId":"ST-221"},{"rackTotCnt":"20","stationName":"165. 중앙근린공원","parkingBikeTotCnt":"17","shared":"85","stationLatitude":"37.57513809","stationLongitude":"126.91394043","stationId":"ST-222"},{"rackTotCnt":"20","stationName":"166. 가재울 초등학교","parkingBikeTotCnt":"13","shared":"65","stationLatitude":"37.57381821","stationLongitude":"126.91923523","stationId":"ST-223"},{"rackTotCnt":"15","stationName":"167. 연가초등학교 옆","parkingBikeTotCnt":"6","shared":"40","stationLatitude":"37.57946014","stationLongitude":"126.91712952","stationId":"ST-224"},{"rackTotCnt":"10","stationName":"169. 북가좌 삼거리","parkingBikeTotCnt":"23","shared":"230","stationLatitude":"37.57300186","stationLongitude":"126.90779877","stationId":"ST-226"},{"rackTotCnt":"10","stationName":"170. DMC파크뷰자이아파트 302동 앞","parkingBikeTotCnt":"4","shared":"40","stationLatitude":"37.57311249","stationLongitude":"126.92244720","stationId":"ST-227"},{"rackTotCnt":"10","stationName":"171. 임광빌딩 앞","parkingBikeTotCnt":"5","shared":"50","stationLatitude":"37.56472397","stationLongitude":"126.96727753","stationId":"ST-228"},{"rackTotCnt":"8","stationName":"173. 서대문역 8번출구 앞","parkingBikeTotCnt":"7","shared":"88","stationLatitude":"37.56477737","stationLongitude":"126.96614838","stationId":"ST-230"},{"rackTotCnt":"15","stationName":"175. 홍연2교옆","parkingBikeTotCnt":"3","shared":"20","stationLatitude":"37.57806778","stationLongitude":"126.93088531","stationId":"ST-231"},{"rackTotCnt":"10","stationName":"176. 명지대학교 도서관","parkingBikeTotCnt":"11","shared":"110","stationLatitude":"37.58109665","stationLongitude":"126.92402649","stationId":"ST-555"},{"rackTotCnt":"8","stationName":"177. 북가좌 초등학교","parkingBikeTotCnt":"12","shared":"150","stationLatitude":"37.57763672","stationLongitude":"126.90965271","stationId":"ST-345"},{"rackTotCnt":"9","stationName":"178. 증산3교 앞","parkingBikeTotCnt":"3","shared":"33","stationLatitude":"37.57987595","stationLongitude":"126.90634918","stationId":"ST-349"},{"rackTotCnt":"14","stationName":"179. 가좌역 4번출구 앞","parkingBikeTotCnt":"16","shared":"114","stationLatitude":"37.56877518","stationLongitude":"126.91529846","stationId":"ST-232"},{"rackTotCnt":"10","stationName":"180. 충정로역 7번출구 아래","parkingBikeTotCnt":"6","shared":"60","stationLatitude":"37.55996704","stationLongitude":"126.96246338","stationId":"ST-233"},{"rackTotCnt":"15","stationName":"181. 망원초록길 입구","parkingBikeTotCnt":"10","shared":"67","stationLatitude":"37.55134201","stationLongitude":"126.90267181","stationId":"ST-339"},{"rackTotCnt":"15","stationName":"183. 하늘채코오롱아파트 건너편","parkingBikeTotCnt":"13","shared":"87","stationLatitude":"37.56538773","stationLongitude":"126.91932678","stationId":"ST-341"},{"rackTotCnt":"8","stationName":"184.망원우체국사거리 인근","parkingBikeTotCnt":"7","shared":"88","stationLatitude":"37.55894852","stationLongitude":"126.90775299","stationId":"ST-342"},{"rackTotCnt":"15","stationName":"185. 마포 신수공원 앞","parkingBikeTotCnt":"1","shared":"7","stationLatitude":"37.54254532","stationLongitude":"126.93429565","stationId":"ST-343"},{"rackTotCnt":"40","stationName":"186. 월드컵공원","parkingBikeTotCnt":"54","shared":"135","stationLatitude":"37.56396484","stationLongitude":"126.89820862","stationId":"ST-344"},{"rackTotCnt":"9","stationName":"188. 홍은동 정원여중 입구","parkingBikeTotCnt":"14","shared":"156","stationLatitude":"37.58638763","stationLongitude":"126.93512726","stationId":"ST-346"},{"rackTotCnt":"10","stationName":"191. 서우빌딩","parkingBikeTotCnt":"15","shared":"150","stationLatitude":"37.57889175","stationLongitude":"126.91073608","stationId":"ST-347"},{"rackTotCnt":"8","stationName":"192. 연서어린이공원","parkingBikeTotCnt":"9","shared":"113","stationLatitude":"37.57222748","stationLongitude":"126.92306519","stationId":"ST-348"},{"rackTotCnt":"10","stationName":"194. 증산교 앞","parkingBikeTotCnt":"22","shared":"220","stationLatitude":"37.57731628","stationLongitude":"126.90296936","stationId":"ST-350"},{"rackTotCnt":"10","stationName":"195. 모래내고가차도 ","parkingBikeTotCnt":"0","shared":"0","stationLatitude":"37.56765747","stationLongitude":"126.91780853","stationId":"ST-351"},{"rackTotCnt":"10","stationName":"198. 충정2교","parkingBikeTotCnt":"6","shared":"60","stationLatitude":"37.56390762","stationLongitude":"126.96497345","stationId":"ST-354"},{"rackTotCnt":"30","stationName":"199. 서울 월드컵 경기장","parkingBikeTotCnt":"42","shared":"140","stationLatitude":"37.56684494","stationLongitude":"126.89644623","stationId":"ST-443"},{"rackTotCnt":"22","stationName":"200. 국회의원회관","parkingBikeTotCnt":"10","shared":"45","stationLatitude":"37.52841568","stationLongitude":"126.91391754","stationId":"ST-45"},{"rackTotCnt":"15","stationName":"201. 진미파라곤 앞","parkingBikeTotCnt":"4","shared":"27","stationLatitude":"37.53123856","stationLongitude":"126.92133331","stationId":"ST-46"},{"rackTotCnt":"30","stationName":"202. 국민일보 앞","parkingBikeTotCnt":"60","shared":"200","stationLatitude":"37.52881622","stationLongitude":"126.92453003","stationId":"ST-47"},{"rackTotCnt":"15","stationName":"203. 국회의사당역 3번출구 옆","parkingBikeTotCnt":"28","shared":"187","stationLatitude":"37.52805710","stationLongitude":"126.91870117","stationId":"ST-51"},{"rackTotCnt":"13","stationName":"204. 국회의사당역 5번출구 옆","parkingBikeTotCnt":"16","shared":"123","stationLatitude":"37.52816391","stationLongitude":"126.91702271","stationId":"ST-50"},{"rackTotCnt":"20","stationName":"205. 산업은행 앞","parkingBikeTotCnt":"25","shared":"125","stationLatitude":"37.52626419","stationLongitude":"126.92050934","stationId":"ST-52"},{"rackTotCnt":"35","stationName":"206. KBS 앞","parkingBikeTotCnt":"53","shared":"151","stationLatitude":"37.52466583","stationLongitude":"126.91802216","stationId":"ST-53"},{"rackTotCnt":"46","stationName":"207. 여의나루역 1번출구 앞","parkingBikeTotCnt":"1","shared":"2","stationLatitude":"37.52715683","stationLongitude":"126.93190002","stationId":"ST-73"},{"rackTotCnt":"22","stationName":"209. 유진투자증권빌딩 앞","parkingBikeTotCnt":"59","shared":"268","stationLatitude":"37.52461243","stationLongitude":"126.92783356","stationId":"ST-55"},{"rackTotCnt":"19","stationName":"213. KT앞","parkingBikeTotCnt":"27","shared":"142","stationLatitude":"37.52190781","stationLongitude":"126.91895294","stationId":"ST-59"},{"rackTotCnt":"21","stationName":"214. 금융감독원 앞","parkingBikeTotCnt":"31","shared":"148","stationLatitude":"37.52302170","stationLongitude":"126.92083740","stationId":"ST-60"},{"rackTotCnt":"15","stationName":"217. NH농협은행 앞","parkingBikeTotCnt":"73","shared":"487","stationLatitude":"37.52207947","stationLongitude":"126.93036652","stationId":"ST-66"},{"rackTotCnt":"12","stationName":"219. 롯데캐슬엠파이어 옆","parkingBikeTotCnt":"9","shared":"75","stationLatitude":"37.52069473","stationLongitude":"126.92583466","stationId":"ST-62"},{"rackTotCnt":"30","stationName":"220. 미성아파트 A동 앞","parkingBikeTotCnt":"17","shared":"57","stationLatitude":"37.51936340","stationLongitude":"126.92604828","stationId":"ST-63"},{"rackTotCnt":"10","stationName":"221. 여의도초교 앞","parkingBikeTotCnt":"2","shared":"20","stationLatitude":"37.52267456","stationLongitude":"126.93778992","stationId":"ST-67"},{"rackTotCnt":"12","stationName":"222. 시범아파트버스정류장 옆","parkingBikeTotCnt":"24","shared":"200","stationLatitude":"37.51902008","stationLongitude":"126.93688965","stationId":"ST-68"},{"rackTotCnt":"20","stationName":"223. 진주아파트상가 앞","parkingBikeTotCnt":"28","shared":"140","stationLatitude":"37.51913071","stationLongitude":"126.93337250","stationId":"ST-69"},{"rackTotCnt":"20","stationName":"224. 롯데캐슬 앞","parkingBikeTotCnt":"11","shared":"55","stationLatitude":"37.52008820","stationLongitude":"126.93236542","stationId":"ST-70"},{"rackTotCnt":"26","stationName":"225. 앙카라공원 앞","parkingBikeTotCnt":"15","shared":"58","stationLatitude":"37.51758575","stationLongitude":"126.92961884","stationId":"ST-71"},{"rackTotCnt":"19","stationName":"226. 샛강역 1번출구 앞","parkingBikeTotCnt":"15","shared":"79","stationLatitude":"37.51776505","stationLongitude":"126.92841339","stationId":"ST-72"},{"rackTotCnt":"20","stationName":"227. 양평1나들목 보행통로 입구","parkingBikeTotCnt":"21","shared":"105","stationLatitude":"37.54466629","stationLongitude":"126.88835907","stationId":"ST-277"},{"rackTotCnt":"10","stationName":"228. 선유도역 3번출구 앞","parkingBikeTotCnt":"37","shared":"370","stationLatitude":"37.53845978","stationLongitude":"126.89450836","stationId":"ST-278"},{"rackTotCnt":"25","stationName":"229. 양평1 보행육교 앞","parkingBikeTotCnt":"56","shared":"224","stationLatitude":"37.53587341","stationLongitude":"126.89218140","stationId":"ST-279"},{"rackTotCnt":"13","stationName":"230. 영등포구청역 7번출구","parkingBikeTotCnt":"9","shared":"69","stationLatitude":"37.52435684","stationLongitude":"126.89600372","stationId":"ST-413"},{"rackTotCnt":"10","stationName":"231. 남부고용노동지청 남측","parkingBikeTotCnt":"6","shared":"60","stationLatitude":"37.52450562","stationLongitude":"126.89182281","stationId":"ST-280"},{"rackTotCnt":"20","stationName":"232. 양평우림 이비즈센타 앞","parkingBikeTotCnt":"19","shared":"95","stationLatitude":"37.52565002","stationLongitude":"126.88781738","stationId":"ST-281"},{"rackTotCnt":"10","stationName":"233. 양평1동 YP센터 앞","parkingBikeTotCnt":"32","shared":"320","stationLatitude":"37.52848816","stationLongitude":"126.89164734","stationId":"ST-282"},{"rackTotCnt":"10","stationName":"236. 문래동자이아파트 앞","parkingBikeTotCnt":"8","shared":"80","stationLatitude":"37.51615524","stationLongitude":"126.89461517","stationId":"ST-285"},{"rackTotCnt":"20","stationName":"237. 보라매 두산위브 건너편","parkingBikeTotCnt":"14","shared":"70","stationLatitude":"37.49652100","stationLongitude":"126.91492462","stationId":"ST-286"},{"rackTotCnt":"17","stationName":"238. 제2구민체육센타 앞","parkingBikeTotCnt":"22","shared":"129","stationLatitude":"37.52638626","stationLongitude":"126.90275574","stationId":"ST-287"},{"rackTotCnt":"19","stationName":"239. 유스호스텔 앞","parkingBikeTotCnt":"31","shared":"163","stationLatitude":"37.52585220","stationLongitude":"126.90328217","stationId":"ST-288"},{"rackTotCnt":"10","stationName":"240. 문래역 4번출구 앞","parkingBikeTotCnt":"15","shared":"150","stationLatitude":"37.51873779","stationLongitude":"126.89557648","stationId":"ST-289"},{"rackTotCnt":"10","stationName":"241. 신길우성1차아파트 앞 공원","parkingBikeTotCnt":"3","shared":"30","stationLatitude":"37.50501633","stationLongitude":"126.89853668","stationId":"ST-290"},{"rackTotCnt":"15","stationName":"242. 신길선원가와인아파트 앞","parkingBikeTotCnt":"3","shared":"20","stationLatitude":"37.51093292","stationLongitude":"126.91022491","stationId":"ST-291"},{"rackTotCnt":"15","stationName":"243. 이앤씨드림타워 앞","parkingBikeTotCnt":"42","shared":"280","stationLatitude":"37.52708435","stationLongitude":"126.89138031","stationId":"ST-292"},{"rackTotCnt":"20","stationName":"244. 영등포삼환아파트 앞","parkingBikeTotCnt":"52","shared":"260","stationLatitude":"37.53007889","stationLongitude":"126.90570831","stationId":"ST-293"},{"rackTotCnt":"14","stationName":"245. 삼성생명 당산사옥 앞","parkingBikeTotCnt":"34","shared":"243","stationLatitude":"37.52826

**데이터셋 정보**

- rackTotCnt: 거치대개수
- stationName: 대여소이름
- parkingBikeTotCnt: 자전거주차총건수
- shared: 거치율
- stationLatitude: 위도
- stationLongitude: 경도
- stationId: 대여소ID

## 1.2. 서울시 공공자전거 실시간 대여정보 모든 데이터 가져오기

- 위 실습 결과로 작성된 구문을 수정하여 모든 데이터를 가져와 **bike** 데이터프레임을 다시 만듭니다.
- while 문을 사용해 JSON 문자열을 연결 한 후 이후 과정을 진행합니다.

In [53]:
start = 1
end = 1000
result = []
while True:

  start += 1000
  end += 1000

  url = f'http://openapi.seoul.go.kr:8088/{key}/{res_type}/bikeList/{start}/{end}'
  response = urllib.request.urlopen(url)
  json_str = response.read().decode('utf-8')
  # print(json_str)
  json_object = json.loads(json_str)
  bike = pd.json_normalize(json_object['rentBikeStatus']['row'])
  result.append(bike)

  # print(json_object['rentBikeStatus']['list_total_count'])
  if int(json_object['rentBikeStatus']['list_total_count']) < 1000:
    break
print(result.info())

AttributeError: 'list' object has no attribute 'info'

- 하위 데이터를 확인합니다.

In [45]:
json_object = json.loads(json_str)
print(json_object)

# result = json_object['rentBikeStatus']['row']

# 데이터 플레임으로 변환
bike = pd.json_normalize(json_object['rentBikeStatus']['row'])
bike

{'rentBikeStatus': {'list_total_count': 1000, 'RESULT': {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다.'}, 'row': [{'rackTotCnt': '7', 'stationName': '1520. 수유중앙시장', 'parkingBikeTotCnt': '9', 'shared': '129', 'stationLatitude': '37.63986206', 'stationLongitude': '127.02278900', 'stationId': 'ST-650'}, {'rackTotCnt': '10', 'stationName': '1525. 미아동 복합청사', 'parkingBikeTotCnt': '3', 'shared': '30', 'stationLatitude': '37.62714005', 'stationLongitude': '127.02669525', 'stationId': 'ST-647'}, {'rackTotCnt': '10', 'stationName': '1527. 미아역 1번 출구 뒤', 'parkingBikeTotCnt': '8', 'shared': '80', 'stationLatitude': '37.62733459', 'stationLongitude': '127.02605438', 'stationId': 'ST-1101'}, {'rackTotCnt': '10', 'stationName': '1528. 삼각산동 주민센터', 'parkingBikeTotCnt': '2', 'shared': '20', 'stationLatitude': '37.61503601', 'stationLongitude': '127.02069855', 'stationId': 'ST-1102'}, {'rackTotCnt': '15', 'stationName': '1529. 미아동 한국전력공사', 'parkingBikeTotCnt': '31', 'shared': '207', 'stationLatitude': '37.63018036', 'stationLongitude': '127.02490997', 'stationId': 'ST-1103'}, {'rackTotCnt': '13', 'stationName': '1530. 광산사거리', 'parkingBikeTotCnt': '26', 'shared': '200', 'stationLatitude': '37.64355087', 'stationLongitude': '127.02234650', 'stationId': 'ST-1104'}, {'rackTotCnt': '10', 'stationName': '1531. 미아사거리 1번 출구', 'parkingBikeTotCnt': '47', 'shared': '470', 'stationLatitude': '37.61395645', 'stationLongitude': '127.03025055', 'stationId': 'ST-1105'}, {'rackTotCnt': '10', 'stationName': '1532. 번3동 주민센터 교차로', 'parkingBikeTotCnt': '17', 'shared': '170', 'stationLatitude': '37.62635422', 'stationLongitude': '127.04744720', 'stationId': 'ST-1106'}, {'rackTotCnt': '10', 'stationName': '1533. 번동 주공3, 4단지 교차로', 'parkingBikeTotCnt': '17', 'shared': '170', 'stationLatitude': '37.62991714', 'stationLongitude': '127.04091644', 'stationId': 'ST-1107'}, {'rackTotCnt': '10', 'stationName': '1535. 효성인텔리안 앞', 'parkingBikeTotCnt': '3', 'shared': '30', 'stationLatitude': '37.63629150', 'stationLongitude': '127.02337646', 'stationId': 'ST-1109'}, {'rackTotCnt': '20', 'stationName': '1536. 번동 두산위브 101동 옆', 'parkingBikeTotCnt': '8', 'shared': '40', 'stationLatitude': '37.63626099', 'stationLongitude': '127.03217316', 'stationId': 'ST-1110'}, {'rackTotCnt': '10', 'stationName': '1537. 북한산 우이역', 'parkingBikeTotCnt': '7', 'shared': '70', 'stationLatitude': '37.66366577', 'stationLongitude': '127.01242828', 'stationId': 'ST-1387'}, {'rackTotCnt': '8', 'stationName': '1538. 솔밭공원역', 'parkingBikeTotCnt': '3', 'shared': '38', 'stationLatitude': '37.65615845', 'stationLongitude': '127.01313782', 'stationId': 'ST-1388'}, {'rackTotCnt': '10', 'stationName': '1539. 4.19민주묘지역', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.64967346', 'stationLongitude': '127.01345062', 'stationId': 'ST-1389'}, {'rackTotCnt': '8', 'stationName': '1540. 가오리역', 'parkingBikeTotCnt': '10', 'shared': '125', 'stationLatitude': '37.64167023', 'stationLongitude': '127.01688385', 'stationId': 'ST-1390'}, {'rackTotCnt': '10', 'stationName': '1541. 삼양역', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.62652969', 'stationLongitude': '127.01805878', 'stationId': 'ST-1391'}, {'rackTotCnt': '10', 'stationName': '1542. 삼양사거리역', 'parkingBikeTotCnt': '1', 'shared': '10', 'stationLatitude': '37.62155151', 'stationLongitude': '127.02037048', 'stationId': 'ST-1392'}, {'rackTotCnt': '10', 'stationName': '1543. 수유1동 주민센터', 'parkingBikeTotCnt': '2', 'shared': '20', 'stationLatitude': '37.63018799', 'stationLongitude': '127.01773834', 'stationId': 'ST-1423'}, {'rackTotCnt': '10', 'stationName': '1546. 송천동우체국', 'parkingBikeTotCnt': '24', 'shared': '240', 'stationLatitude': '37.61545944', 'stationLongitude': '127.02970123', 'stationId': 'ST-1665'}, {'rackTotCnt': '10', 'stationName': '1547. 꿈의숲 롯데캐슬', 'parkingBikeTotCnt': '6', 'shared': '60', 'stationLatitude': '37.61775208', 'stationLongitude': '127.03570557', 'stationId': 'ST-1724'}, {'rackTotCnt': '15', 'stationName': '1548. 북서울 꿈의숲 서문', 'parkingBikeTotCnt': '2', 'shared': '13', 'stationLatitude': '37.62268829', 'stationLongitude': '127.03781128', 'stationId': 'ST-1725'}, {'rackTotCnt': '10', 'stationName': '1550.삼각산아이원아파트(105동 옆)', 'parkingBikeTotCnt': '5', 'shared': '50', 'stationLatitude': '37.61522293', 'stationLongitude': '127.01850891', 'stationId': 'ST-2123'}, {'rackTotCnt': '8', 'stationName': '1551.4.19탑 앞', 'parkingBikeTotCnt': '3', 'shared': '38', 'stationLatitude': '37.64686203', 'stationLongitude': '127.00881195', 'stationId': 'ST-2124'}, {'rackTotCnt': '8', 'stationName': '1552. 강북구청사거리', 'parkingBikeTotCnt': '6', 'shared': '75', 'stationLatitude': '37.63920212', 'stationLongitude': '127.02723694', 'stationId': 'ST-2125'}, {'rackTotCnt': '15', 'stationName': '1553.서울북부고용노동지청', 'parkingBikeTotCnt': '1', 'shared': '7', 'stationLatitude': '37.63520432', 'stationLongitude': '127.03396606', 'stationId': 'ST-2126'}, {'rackTotCnt': '10', 'stationName': '1554.번동사거리', 'parkingBikeTotCnt': '1', 'shared': '10', 'stationLatitude': '37.63539124', 'stationLongitude': '127.03455353', 'stationId': 'ST-2127'}, {'rackTotCnt': '10', 'stationName': '1557.신창교', 'parkingBikeTotCnt': '22', 'shared': '220', 'stationLatitude': '37.63238144', 'stationLongitude': '127.03930664', 'stationId': 'ST-2129'}, {'rackTotCnt': '10', 'stationName': '1558.강북문화정보도서관', 'parkingBikeTotCnt': '1', 'shared': '10', 'stationLatitude': '37.62552643', 'stationLongitude': '127.03732300', 'stationId': 'ST-2130'}, {'rackTotCnt': '10', 'stationName': '1560. 도봉세무서 앞', 'parkingBikeTotCnt': '12', 'shared': '120', 'stationLatitude': '37.61980820', 'stationLongitude': '127.02852631', 'stationId': 'ST-2132'}, {'rackTotCnt': '6', 'stationName': '1564.4.19민주묘지역 1번출구', 'parkingBikeTotCnt': '4', 'shared': '67', 'stationLatitude': '37.64959717', 'stationLongitude': '127.01384735', 'stationId': 'ST-2133'}, {'rackTotCnt': '15', 'stationName': '1565.수유사거리', 'parkingBikeTotCnt': '3', 'shared': '20', 'stationLatitude': '37.63561249', 'stationLongitude': '127.02299500', 'stationId': 'ST-2134'}, {'rackTotCnt': '14', 'stationName': '1568.4.19민주묘지 입구사거리', 'parkingBikeTotCnt': '3', 'shared': '21', 'stationLatitude': '37.64793396', 'stationLongitude': '127.01457214', 'stationId': 'ST-2136'}, {'rackTotCnt': '10', 'stationName': '1569.수유역2번출구', 'parkingBikeTotCnt': '14', 'shared': '140', 'stationLatitude': '37.63796997', 'stationLongitude': '127.02590179', 'stationId': 'ST-2137'}, {'rackTotCnt': '10', 'stationName': '1571.북서울 꿈의 숲 입구', 'parkingBikeTotCnt': '5', 'shared': '50', 'stationLatitude': '37.62657166', 'stationLongitude': '127.03864288', 'stationId': 'ST-2401'}, {'rackTotCnt': '10', 'stationName': '1572. 우이동 먹거리마을', 'parkingBikeTotCnt': '3', 'shared': '30', 'stationLatitude': '37.66446304', 'stationLongitude': '127.01184082', 'stationId': 'ST-2402'}, {'rackTotCnt': '10', 'stationName': '1573.현대성우아파트 옆', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.61666489', 'stationLongitude': '127.02210999', 'stationId': 'ST-2403'}, {'rackTotCnt': '8', 'stationName': '1574.송중초등학교 옆', 'parkingBikeTotCnt': '26', 'shared': '325', 'stationLatitude': '37.61669922', 'stationLongitude': '127.03049469', 'stationId': 'ST-2405'}, {'rackTotCnt': '10', 'stationName': '1601. 석계역 문화광장 내 자전거 보관소', 'parkingBikeTotCnt': '45', 'shared': '450', 'stationLatitude': '37.61518097', 'stationLongitude': '127.06464386', 'stationId': 'ST-600'}, {'rackTotCnt': '13', 'stationName': '1602. 광운대역 앞', 'parkingBikeTotCnt': '9', 'shared': '69', 'stationLatitude': '37.62266159', 'stationLongitude': '127.06189728', 'stationId': 'ST-913'}, {'rackTotCnt': '10', 'stationName': '1605. 헬스케어', 'parkingBikeTotCnt': '4', 'shared': '40', 'stationLatitude': '37.63162231', 'stationLongitude': '127.06161499', 'stationId': 'ST-866'}, {'rackTotCnt': '10', 'stationName': '1606. 태릉입구역 3번출구 ', 'parkingBikeTotCnt': '8', 'shared': '80', 'stationLatitude': '37.61917114', 'stationLongitude': '127.07492828', 'stationId': 'ST-602'}, {'rackTotCnt': '9', 'stationName': '1608. 공릉역 1번 출구 앞', 'parkingBikeTotCnt': '2', 'shared': '22', 'stationLatitude': '37.62661362', 'stationLongitude': '127.07275391', 'stationId': 'ST-735'}, {'rackTotCnt': '20', 'stationName': '1610. 화랑대역 2번출구 앞', 'parkingBikeTotCnt': '49', 'shared': '245', 'stationLatitude': '37.62036896', 'stationLongitude': '127.08364105', 'stationId': 'ST-603'}, {'rackTotCnt': '25', 'stationName': '1611. 과기대 입구(우)', 'parkingBikeTotCnt': '6', 'shared': '24', 'stationLatitude': '37.62957382', 'stationLongitude': '127.07678986', 'stationId': 'ST-604'}, {'rackTotCnt': '10', 'stationName': '1616. 하계2동 공항버스정류장 옆', 'parkingBikeTotCnt': '2', 'shared': '20', 'stationLatitude': '37.63510895', 'stationLongitude': '127.06832886', 'stationId': 'ST-605'}, {'rackTotCnt': '7', 'stationName': '1617. 하계동 중평어린이공원 앞', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.63756943', 'stationLongitude': '127.06315613', 'stationId': 'ST-606'}, {'rackTotCnt': '10', 'stationName': '1619. 중계동 하나프라자빌딩 앞(중1-1)', 'parkingBikeTotCnt': '1', 'shared': '10', 'stationLatitude': '37.64902115', 'stationLongitude': '127.07640839', 'stationId': 'ST-736'}, {'rackTotCnt': '20', 'stationName': '1625. 상계역 3번출구', 'parkingBikeTotCnt': '4', 'shared': '20', 'stationLatitude': '37.65999985', 'stationLongitude': '127.07296753', 'stationId': 'ST-914'}, {'rackTotCnt': '12', 'stationName': '1627. 수락산역 4번출구', 'parkingBikeTotCnt': '1', 'shared': '8', 'stationLatitude': '37.67694092', 'stationLongitude': '127.05509949', 'stationId': 'ST-915'}, {'rackTotCnt': '5', 'stationName': '1628. 노일초등학교 앞', 'parkingBikeTotCnt': '2', 'shared': '40', 'stationLatitude': '37.67456055', 'stationLongitude': '127.05513763', 'stationId': 'ST-868'}, {'rackTotCnt': '10', 'stationName': '1630. 수연빌딩 앞', 'parkingBikeTotCnt': '18', 'shared': '180', 'stationLatitude': '37.67625046', 'stationLongitude': '127.05550385', 'stationId': 'ST-869'}, {'rackTotCnt': '15', 'stationName': '1634. 당고개공원 대여소', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.66846085', 'stationLongitude': '127.07714844', 'stationId': 'ST-608'}, {'rackTotCnt': '6', 'stationName': '1635. 상계3,4동 주민센터 대여소', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.67271042', 'stationLongitude': '127.08316040', 'stationId': 'ST-609'}, {'rackTotCnt': '10', 'stationName': '1636. 상계주공2단지 버스정류장 옆', 'parkingBikeTotCnt': '5', 'shared': '50', 'stationLatitude': '37.64921188', 'stationLongitude': '127.06176758', 'stationId': 'ST-610'}, {'rackTotCnt': '9', 'stationName': '1637. KT 전화국 버스정류장 옆', 'parkingBikeTotCnt': '6', 'shared': '67', 'stationLatitude': '37.65466690', 'stationLongitude': '127.06372833', 'stationId': 'ST-611'}, {'rackTotCnt': '10', 'stationName': '1639. 희성오피앙', 'parkingBikeTotCnt': '15', 'shared': '150', 'stationLatitude': '37.68031311', 'stationLongitude': '127.05506897', 'stationId': 'ST-612'}, {'rackTotCnt': '9', 'stationName': '1640. 한내근린공원 북측', 'parkingBikeTotCnt': '43', 'shared': '478', 'stationLatitude': '37.62386322', 'stationLongitude': '127.06848907', 'stationId': 'ST-971'}, {'rackTotCnt': '15', 'stationName': '1641. 한내근린공원 남측', 'parkingBikeTotCnt': '25', 'shared': '167', 'stationLatitude': '37.62155533', 'stationLongitude': '127.06951141', 'stationId': 'ST-970'}, {'rackTotCnt': '7', 'stationName': '1642. 서울여대 남문', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.62531662', 'stationLongitude': '127.08813477', 'stationId': 'ST-964'}, {'rackTotCnt': '10', 'stationName': '1643. 태릉입구역 8번출구', 'parkingBikeTotCnt': '31', 'shared': '310', 'stationLatitude': '37.61736679', 'stationLongitude': '127.07521057', 'stationId': 'ST-1111'}, {'rackTotCnt': '10', 'stationName': '1646. 삼육대 입구', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.63848877', 'stationLongitude': '127.10790253', 'stationId': 'ST-1114'}, {'rackTotCnt': '25', 'stationName': '1650. 중계근린공원내', 'parkingBikeTotCnt': '13', 'shared': '52', 'stationLatitude': '37.63957977', 'stationLongitude': '127.06510162', 'stationId': 'ST-1118'}, {'rackTotCnt': '20', 'stationName': '1651. 상계동 우방유쉘아파트 앞', 'parkingBikeTotCnt': '13', 'shared': '65', 'stationLatitude': '37.67237473', 'stationLongitude': '127.05599213', 'stationId': 'ST-1119'}, {'rackTotCnt': '10', 'stationName': '1652. 파르코 앞', 'parkingBikeTotCnt': '18', 'shared': '180', 'stationLatitude': '37.68000031', 'stationLongitude': '127.05558014', 'stationId': 'ST-1120'}, {'rackTotCnt': '10', 'stationName': '1653. 노원역1번출구', 'parkingBikeTotCnt': '22', 'shared': '220', 'stationLatitude': '37.65620041', 'stationLongitude': '127.06362152', 'stationId': 'ST-1121'}, {'rackTotCnt': '15', 'stationName': '1654. 당고개입구 오거리', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.66379166', 'stationLongitude': '127.07544708', 'stationId': 'ST-1122'}, {'rackTotCnt': '15', 'stationName': '1655. 공릉1단지아파트', 'parkingBikeTotCnt': '18', 'shared': '120', 'stationLatitude': '37.63111115', 'stationLongitude': '127.07015991', 'stationId': 'ST-1123'}, {'rackTotCnt': '12', 'stationName': '1656. 중앙하이츠 아파트 입구', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.65501785', 'stationLongitude': '127.06750488', 'stationId': 'ST-1124'}, {'rackTotCnt': '20', 'stationName': '1657. 노원구청 ', 'parkingBikeTotCnt': '35', 'shared': '175', 'stationLatitude': '37.65404892', 'stationLongitude': '127.05732727', 'stationId': 'ST-1125'}, {'rackTotCnt': '10', 'stationName': '1659. 중계동 을지중학교', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.65032959', 'stationLongitude': '127.07160187', 'stationId': 'ST-1127'}, {'rackTotCnt': '8', 'stationName': '1660. 서울시립과학관', 'parkingBikeTotCnt': '1', 'shared': '13', 'stationLatitude': '37.64207077', 'stationLongitude': '127.07662201', 'stationId': 'ST-1128'}, {'rackTotCnt': '10', 'stationName': '1661. 당현천근린공원', 'parkingBikeTotCnt': '4', 'shared': '40', 'stationLatitude': '37.64963913', 'stationLongitude': '127.06560516', 'stationId': 'ST-1278'}, {'rackTotCnt': '20', 'stationName': '1662. 노원역7번출구', 'parkingBikeTotCnt': '35', 'shared': '175', 'stationLatitude': '37.65421677', 'stationLongitude': '127.05921173', 'stationId': 'ST-1279'}, {'rackTotCnt': '25', 'stationName': '1663. 동해문화예술관앞', 'parkingBikeTotCnt': '25', 'shared': '100', 'stationLatitude': '37.61938095', 'stationLongitude': '127.05785370', 'stationId': 'ST-1280'}, {'rackTotCnt': '10', 'stationName': '1664. 노해근린공원내', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.64936066', 'stationLongitude': '127.07044220', 'stationId': 'ST-1281'}, {'rackTotCnt': '10', 'stationName': '1665. 양지근린공원앞', 'parkingBikeTotCnt': '1', 'shared': '10', 'stationLatitude': '37.64699554', 'stationLongitude': '127.07640076', 'stationId': 'ST-1282'}, {'rackTotCnt': '10', 'stationName': '1666. 노원소방서인근', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.65578079', 'stationLongitude': '127.07177734', 'stationId': 'ST-1283'}, {'rackTotCnt': '10', 'stationName': '1667. 중계중학교', 'parkingBikeTotCnt': '1', 'shared': '10', 'stationLatitude': '37.65449905', 'stationLongitude': '127.07438660', 'stationId': 'ST-1284'}, {'rackTotCnt': '10', 'stationName': '1668. 중계역 6번출구', 'parkingBikeTotCnt': '17', 'shared': '170', 'stationLatitude': '37.64556503', 'stationLongitude': '127.06334686', 'stationId': 'ST-1285'}, {'rackTotCnt': '9', 'stationName': '1669. 중계역 3번출구', 'parkingBikeTotCnt': '22', 'shared': '244', 'stationLatitude': '37.64352798', 'stationLongitude': '127.06522369', 'stationId': 'ST-1286'}, {'rackTotCnt': '20', 'stationName': '1670. 노원경찰서교차로', 'parkingBikeTotCnt': '2', 'shared': '10', 'stationLatitude': '37.64340973', 'stationLongitude': '127.07183838', 'stationId': 'ST-1287'}, {'rackTotCnt': '15', 'stationName': '1671. 인덕대학교', 'parkingBikeTotCnt': '13', 'shared': '87', 'stationLatitude': '37.62934875', 'stationLongitude': '127.05482483', 'stationId': 'ST-1288'}, {'rackTotCnt': '15', 'stationName': '1672. 상계동수락리버시티', 'parkingBikeTotCnt': '26', 'shared': '173', 'stationLatitude': '37.68859863', 'stationLongitude': '127.05340576', 'stationId': 'ST-1289'}, {'rackTotCnt': '15', 'stationName': '1674. 서울북부고용센터앞', 'parkingBikeTotCnt': '15', 'shared': '100', 'stationLatitude': '37.65354919', 'stationLongitude': '127.05808258', 'stationId': 'ST-1291'}, {'rackTotCnt': '9', 'stationName': '1675. 월계문화체육센터', 'parkingBikeTotCnt': '13', 'shared': '144', 'stationLatitude': '37.62694168', 'stationLongitude': '127.05513000', 'stationId': 'ST-1348'}, {'rackTotCnt': '15', 'stationName': '1677. 육군사관학교  앞', 'parkingBikeTotCnt': '23', 'shared': '153', 'stationLatitude': '37.62316513', 'stationLongitude': '127.09049988', 'stationId': 'ST-1349'}, {'rackTotCnt': '10', 'stationName': '1679. 삼육대 도서관', 'parkingBikeTotCnt': '13', 'shared': '130', 'stationLatitude': '37.64282990', 'stationLongitude': '127.10666656', 'stationId': 'ST-1395'}, {'rackTotCnt': '7', 'stationName': '1680. 삼육대 제3과학관', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.64265442', 'stationLongitude': '127.10838318', 'stationId': 'ST-1396'}, {'rackTotCnt': '12', 'stationName': '1681. 현대6차 아파트', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.64580154', 'stationLongitude': '127.08226013', 'stationId': 'ST-1425'}, {'rackTotCnt': '12', 'stationName': '1682. 중계종합사회복지관 교차로', 'parkingBikeTotCnt': '6', 'shared': '50', 'stationLatitude': '37.65745163', 'stationLongitude': '127.07680511', 'stationId': 'ST-1426'}, {'rackTotCnt': '5', 'stationName': '1683. 노원문화예술회관', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.65045929', 'stationLongitude': '127.08088684', 'stationId': 'ST-1473'}, {'rackTotCnt': '20', 'stationName': '1684. 태릉입구역 5번출구', 'parkingBikeTotCnt': '13', 'shared': '65', 'stationLatitude': '37.61832047', 'stationLongitude': '127.07563019', 'stationId': 'ST-1474'}, {'rackTotCnt': '6', 'stationName': '1685. 불암고등학교 앞 횡단보도', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.64818954', 'stationLongitude': '127.08048248', 'stationId': 'ST-1475'}, {'rackTotCnt': '15', 'stationName': '1686. 상계주공10단지 종합상가 앞', 'parkingBikeTotCnt': '1', 'shared': '7', 'stationLatitude': '37.66114044', 'stationLongitude': '127.05805206', 'stationId': 'ST-1476'}, {'rackTotCnt': '9', 'stationName': '1688. 마들역 7번출구', 'parkingBikeTotCnt': '5', 'shared': '56', 'stationLatitude': '37.66566086', 'stationLongitude': '127.05729675', 'stationId': 'ST-1639'}, {'rackTotCnt': '10', 'stationName': '1689. 마들역 3번출구', 'parkingBikeTotCnt': '2', 'shared': '20', 'stationLatitude': '37.66524887', 'stationLongitude': '127.05789185', 'stationId': 'ST-1640'}, {'rackTotCnt': '10', 'stationName': '1690. 도봉운전면허시험장 버스정류장 옆', 'parkingBikeTotCnt': '7', 'shared': '70', 'stationLatitude': '37.65773010', 'stationLongitude': '127.05931091', 'stationId': 'ST-1641'}, {'rackTotCnt': '10', 'stationName': '1691. 노원정보도서관', 'parkingBikeTotCnt': '6', 'shared': '60', 'stationLatitude': '37.66072845', 'stationLongitude': '127.06513214', 'stationId': 'ST-1642'}, {'rackTotCnt': '10', 'stationName': '1692. 온곡초교 교차로', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.66418839', 'stationLongitude': '127.06600952', 'stationId': 'ST-1672'}, {'rackTotCnt': '10', 'stationName': '1693. 원자력 병원', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.62818909', 'stationLongitude': '127.08210754', 'stationId': 'ST-1740'}, {'rackTotCnt': '10', 'stationName': '1696.수락리버시티4단지', 'parkingBikeTotCnt': '12', 'shared': '120', 'stationLatitude': '37.68645096', 'stationLongitude': '127.05283356', 'stationId': 'ST-2062'}, {'rackTotCnt': '10', 'stationName': '1697.상계주공2단지 219동', 'parkingBikeTotCnt': '0', 'shared': '0', 'stationLatitude': '37.65024948', 'stationLongitude': '127.05715179', 'stationId': 'ST-2063'}, {'rackTotCnt': '10', 'stationName': '1702. 녹천역 1번출구 앞', 'parkingBikeTotCnt': '14', 'shared': '140', 'stationLatitude': '37.64582062', 'stationLongitude': '127.05042267', 'stationId': 'ST-613'}, {'rackTotCnt': '10', 'stationName': '1703. 도봉산광역환승센터앞 ', 'parkingBikeTotCnt': '7', 'shared': '70', 'stationLatitude': '37.6897

,rackTotCnt,stationName,parkingBikeTotCnt,shared,stationLatitude,stationLongitude,stationId
0,7,1520. 수유중앙시장,9,129,37.63986206,127.02278900,ST-650
1,10,1525. 미아동 복합청사,3,30,37.62714005,127.02669525,ST-647
2,10,1527. 미아역 1번 출구 뒤,8,80,37.62733459,127.02605438,ST-1101
3,10,1528. 삼각산동 주민센터,2,20,37.61503601,127.02069855,ST-1102
4,15,1529. 미아동 한국전력공사,31,207,37.63018036,127.02490997,ST-1103
...,...,...,...,...,...,...,...
995,10,3907. 신도림7차e편한세상아파트 806동 앞,5,50,37.50862503,126.88353729,ST-2559
996,10,3908. 오류동 다숲오피스텔 앞,21,210,37.49267197,126.84162140,ST-2753
997,10,3910. 목양전원교회 앞 로터리,9,90,37.48389053,126.82218170,ST-2828
998,10,3911. 항동하버리안2단지아파트 후문,5,50,37.48337555,126.82247925,ST-2829
999,10,3912. 삼호아파트 앞,8,80,37.49385834,126.85646820,ST-2855

## 1.3. 실시간 대여정보 분석

### 1.3.1.데이터 탐색 및 전처리

- 열 이름, 데이터 형식 등 열 정보를 확인합니다.

In [13]:
bike.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rackTotCnt         1000 non-null   str
 1   stationName        1000 non-null   str
 2   parkingBikeTotCnt  1000 non-null   str
 3   shared             1000 non-null   str
 4   stationLatitude    1000 non-null   str
 5   stationLongitude   1000 non-null   str
 6   stationId          1000 non-null   str
dtypes: str(7)
memory usage: 54.8 KB

- 데이터 형식을 int로 변환합니다.
- 대상 열: rackTotCnt, parkingBikeTotCnt, shared
- 구문 예) df['Money'].astype('int')

In [15]:
# 분석을 위해 승하차 인원 컬럼을 숫자형으로 변환
bike[['rackTotCnt', 'parkingBikeTotCnt', 'shared']] = bike[['rackTotCnt', 'parkingBikeTotCnt', 'shared']].astype(int)

- 결과를 확인합니다.

In [16]:

bike.head()

,rackTotCnt,stationName,parkingBikeTotCnt,shared,stationLatitude,stationLongitude,stationId
0,15,102. 망원역 1번출구 앞,29,193,37.55564880,126.91062927,ST-4
1,14,103. 망원역 2번출구 앞,16,114,37.55495071,126.91083527,ST-5
2,13,104. 합정역 1번출구 앞,17,131,37.55073929,126.91508484,ST-6
3,5,105. 합정역 5번출구 앞,2,40,37.55000687,126.91482544,ST-7
4,12,106. 합정역 7번출구 앞,15,125,37.54864502,126.91282654,ST-8

- 기초통계정보를 확인합니다.

In [17]:
bike.describe()

        rackTotCnt  parkingBikeTotCnt       shared
count  1000.000000         1000.00000  1000.000000
mean     13.066000           13.27400   104.510000
std       5.857983           12.93678    95.869896
min       5.000000            0.00000     0.000000
25%      10.000000            4.00000    33.000000
50%      10.000000           10.00000    81.000000
75%      15.000000           19.00000   147.250000
max      51.000000          104.00000   670.000000

### 1.3.2. 가장 많이 거치된 곳 TOP 10

- 자전거가 가장 많이 거치된 곳을 확인하기 위해 parkingBikeTotCnt 열로 내림차순 정렬한 후 상위 10개 행만 출력하세요.

In [18]:
bike_guchi_top10 = bike.sort_values(by='parkingBikeTotCnt',ascending=False).head(10)
bike_guchi_top10

,rackTotCnt,stationName,parkingBikeTotCnt,shared,stationLatitude,stationLongitude,stationId
645,20,1009. 천호역4번출구(현대백화점),104,520,37.53866577,127.12424469,ST-493
794,30,1210. 롯데월드타워(잠실역2번출구 쪽),85,283,37.51312637,127.10095978,ST-891
87,15,217. NH농협은행 앞,73,487,37.52207947,126.93036652,ST-66
381,15,594. 중랑물재생센터(서울새활용플라자),71,473,37.55830383,127.05805969,ST-967
853,30,1291. 서울체육고등학교 앞,67,223,37.52193832,127.13186646,ST-1580
482,10,762. 오목로 무중력지대 앞,67,670,37.52474213,126.87766266,ST-1503
732,10,1132. 등촌역 7번출구,63,630,37.55110931,126.86370850,ST-528
967,10,1455. 상봉역 2번 출구,63,630,37.59632874,127.08589935,ST-1375
810,13,1231. 잠실역 6번출구,62,477,37.51408768,127.09902954,ST-840
744,36,1152. 마곡역교차로,62,172,37.55831146,126.82652283,ST-1064

### 1.3.3. 거치대 수가 가장 많은 곳 TOP 10

- 거치대 수가 가장 많은 곳을 확인하기 위해 rackTotCnt 열로 내림차순 정렬한 후 상위 10개 행만 출력하세요.

In [19]:
bike_rack_top10 = bike.sort_values(by='rackTotCnt',ascending=False).head(10)
bike_rack_top10

,rackTotCnt,stationName,parkingBikeTotCnt,shared,stationLatitude,stationLongitude,stationId
779,51,1193. 마곡센트럴타워 1차,31,61,37.55947113,126.83207703,ST-1688
273,51,450. 효자동 삼거리,16,31,37.58360291,126.97254944,ST-978
83,46,207. 여의나루역 1번출구 앞,1,2,37.52715683,126.93190002,ST-73
533,40,829. 한강대교 북단 교차로,22,55,37.52293015,126.96169281,ST-1326
68,40,186. 월드컵공원,54,135,37.56396484,126.89820862,ST-344
468,40,744. 신목동역 2번 출구,17,43,37.54384232,126.88254547,ST-1015
293,40,474.동대문역사문화공원역 1번출구 뒤편,8,20,37.56629944,127.00849152,ST-1780
247,37,420. 서울시 공공자전거 상암센터,34,92,37.56624603,126.89617920,ST-85
744,36,1152. 마곡역교차로,62,172,37.55831146,126.82652283,ST-1064
18,35,124. 서강대 정문 건너편,41,117,37.55113983,126.93698883,ST-26

### 1.3.4. 지도 시각화

- 위도와 경도 정보가 있으므로 지도상에 거치대 위치를 표시할 수 있습니다.
- 지도 시각화를 위해 folium 라이브러리를 설치합니다.

In [ ]:
# 라이브러리 설치
# %pip install folium

- 위 분석에서 거치대가 가장 많은 곳의 좌표를 지도상에 표시합니다.

In [ ]:
import folium

my_map = folium.Map(location=[],zoom_start=13)