# 1.공공 데이터 포털

- 대한민국 정부가 제공하는 공공데이터 통합 플랫폼.
- 공공기관이 생성 또는 취득하여 관리하고 있는 공공데이터를 한 곳에서 제공하는 통합 창구.
- 손쉽게 공공데이터를 이용할 수 있도록 파일데이터, 오픈API, 시각화 등 다양한 방식으로 제공.
- 누구라도 쉽고 편리한 검색을 통해 원하는 공공데이터를 빠르고 정확하게 찾을 수 있다.

- 우선 xml을 딕셔너리 형태로 변환하는 라이브러리 설치

In [ ]:
# xmltodict 패키지 설치(아나콘다에는 이미 설치 됨)
# %pip install xmltodict

## 1.1.관세청_국가별 수출입실적(GW)

- 관세청 수출입통계정보의 기간, 국가, 국가코드, 수출건수,수출금액, 수입건수 등을 가져온다.

### 1.1.1.데이터 가져오기

In [ ]:
import json
import pandas as pd
import xmltodict
import urllib.request

In [ ]:
# 매개변수
key = 'YOUR_KEY'
strtYymm = 202501
endYymm = 202512
cntyCd = ''

# url 주소
url =f'https://apis.data.go.kr/1220000/nationtrade/getNationtradeList?serviceKey={key}&strtYymm={strtYymm}&endYymm={endYymm}&cntyCd={cntyCd}'

In [ ]:
# 데이터 가져오기
response = urllib.request.urlopen(url)
print(response.status)

200

In [ ]:
# xml -> dict
xml_parse = xmltodict.parse(response)               # XML 데이터를 딕셔너리로 파싱
xml_dict = json.loads(json.dumps(xml_parse))        # json 모듈을 활용해서 json 형식으로 변환하고 딕셔너리로 변환

In [ ]:
xml_dict

{'response': {'header': {'resultCode': '00', 'resultMsg': '정상서비스.'},
  'body': {'items': {'item': [{'balPayments': '3443225952',
      'expCnt': '193178',
      'expDlr': '9282566788',
      'impCnt': '1416582',
      'impDlr': '5839340836',
      'statCd': 'US',
      'statCdCntnKor1': '미국',
      'year': '2025.01'},
     {'balPayments': '-2004621045',
      'expCnt': '91388',
      'expDlr': '9204172269',
      'impCnt': '1225173',
      'impDlr': '11208793314',
      'statCd': 'CN',
      'statCdCntnKor1': '중국',
      'year': '2025.01'},
     {'balPayments': '1792245180',
      'expCnt': '57209',
      'expDlr': '4356972160',
      'impCnt': '145132',
      'impDlr': '2564726980',
      'statCd': 'VN',
      'statCdCntnKor1': '베트남',
      'year': '2025.01'},
     {'balPayments': '210300569',
      'expCnt': '34078',
      'expDlr': '2438188048',
      'impCnt': '20022',
      'impDlr': '2227887479',
      'statCd': 'TW',
      'statCdCntnKor1': '대만',
      'year': '2025.01'},
     {'balPayments': '-1223548429',
      'expCnt': '146929',
      'expDlr': '2363796881',
      'impCnt': '344783',
      'impDlr': '3587345310',
      'statCd': 'JP',
      'statCdCntnKor1': '일본',
      'year': '2025.01'},
     {'balPayments': '1502111293',
      'expCnt': '18142',
      'expDlr': '1685484400',
      'impCnt': '145075',
      'impDlr': '183373107',
      'statCd': 'HK',
      'statCdCntnKor1': '홍콩',
      'year': '2025.01'},
     {'balPayments': '928096823',
      'expCnt': '18165',
      'expDlr': '1463920945',
      'impCnt': '10408',
      'impDlr': '535824122',
      'statCd': 'IN',
      'statCdCntnKor1': '인도',
      'year': '2025.01'},
     {'balPayments': '134187136',
      'expCnt': '42253',
      'expDlr': '1162019513',
      'impCnt': '18404',
      'impDlr': '1027832377',
      'statCd': 'SG',
      'statCdCntnKor1': '싱가포르',
      'year': '2025.01'},
     {'balPayments': '179175548',
      'expCnt': '15031',
      'expDlr': '947164179',
      'impCnt': '6035',
      'impDlr': '767988631',
      'statCd': 'MX',
      'statCdCntnKor1': '멕시코',
      'year': '2025.01'},
     {'balPayments': '-429397344',
      'expCnt': '26784',
      'expDlr': '921581753',
      'impCnt': '10823',
      'impDlr': '1350979097',
      'statCd': 'MY',
      'statCdCntnKor1': '말레이시아',
      'year': '2025.01'},
     {'balPayments': '-1997255017',
      'expCnt': '15080',
      'expDlr': '909426750',
      'impCnt': '46098',
      'impDlr': '2906681767',
      'statCd': 'AU',
      'statCdCntnKor1': '호주',
      'year': '2025.01'},
     {'balPayments': '651665145',
      'expCnt': '25805',
      'expDlr': '880737363',
      'impCnt': '5154',
      'impDlr': '229072218',
      'statCd': 'PH',
      'statCdCntnKor1': '필리핀',
      'year': '2025.01'},
     {'balPayments': '-620017969',
      'expCnt': '12862',
      'expDlr': '769583494',
      'impCnt': '182280',
      'impDlr': '1389601463',
      'statCd': 'DE',
      'statCdCntnKor1': '독일',
      'year': '2025.01'},
     {'balPayments': '684513428',
      'expCnt': '5877',
      'expDlr': '765206162',
      'impCnt': '2266',
      'impDlr': '80692734',
      'statCd': 'PL',
      'statCdCntnKor1': '폴란드',
      'year': '2025.01'},
     {'balPayments': '737928915',
      'expCnt': '26',
      'expDlr': '737986093',
      'impCnt': '19',
      'impDlr': '57178',
      'statCd': 'MH',
      'statCdCntnKor1': '마샬군도',
      'year': '2025.01'},
     {'balPayments': '192078215',
      'expCnt': '18111',
      'expDlr': '734752287',
      'impCnt': '35388',
      'impDlr': '542674072',
      'statCd': 'CA',
      'statCdCntnKor1': '캐나다',
      'year': '2025.01'},
     {'balPayments': '554082782',
      'expCnt': '14543',
      'expDlr': '662302204',
      'impCnt': '2556',
      'impDlr': '108219422',
      'statCd': 'TR',
      'statCdCntnKor1': '튀르키예',
      'year': '2025.01'},
     {'balPayments': '163581432',
      'expCnt': '17639',
      'expDlr': '624224814',
      'impCnt': '42817',
      'impDlr': '460643382',
      'statCd': 'TH',
      'statCdCntnKor1': '태국',
      'year': '2025.01'},
     {'balPayments': '224066443',
      'expCnt': '16092',
      'expDlr': '556946982',
      'impCnt': '29145',
      'impDlr': '332880539',
      'statCd': 'GB',
      'statCdCntnKor1': '영국',
      'year': '2025.01'},
     {'balPayments': '-562973689',
      'expCnt': '12319',
      'expDlr': '551655213',
      'impCnt': '8931',
      'impDlr': '1114628902',
      'statCd': 'ID',
      'statCdCntnKor1': '인도네시아',
      'year': '2025.01'},
     {'balPayments': '-6266128',
      'expCnt': '6309',
      'expDlr': '476678490',
      'impCnt': '19289',
      'impDlr': '482944618',
      'statCd': 'FR',
      'statCdCntnKor1': '프랑스',
      'year': '2025.01'},
     {'balPayments': '-26294992',
      'expCnt': '8910',
      'expDlr': '458101813',
      'impCnt': '5392',
      'impDlr': '484396805',
      'statCd': 'NL',
      'statCdCntnKor1': '네덜란드',
      'year': '2025.01'},
     {'balPayments': '457783206',
      'expCnt': '57',
      'expDlr': '457792875',
      'impCnt': '29',
      'impDlr': '9669',
      'statCd': 'LR',
      'statCdCntnKor1': '라이베리아',
      'year': '2025.01'},
     {'balPayments': '-282366320',
      'expCnt': '7368',
      'expDlr': '405356891',
      'impCnt': '1627',
      'impDlr': '687723211',
      'statCd': 'BR',
      'statCdCntnKor1': '브라질',
      'year': '2025.01'},
     {'balPayments': '-124249619',
      'expCnt': '5694',
      'expDlr': '336927313',
      'impCnt': '28493',
      'impDlr': '461176932',
      'statCd': 'IT',
      'statCdCntnKor1': '이탈리아',
      'year': '2025.01'},
     {'balPayments': '-1127459172',
      'expCnt': '8682',
      'expDlr': '329442024',
      'impCnt': '460',
      'impDlr': '1456901196',
      'statCd': 'AE',
      'statCdCntnKor1': '아랍에미리트 연합',
      'year': '2025.01'},
     {'balPayments': '187935350',
      'expCnt': '2372',
      'expDlr': '312584293',
      'impCnt': '2247',
      'impDlr': '124648943',
      'statCd': 'BE',
      'statCdCntnKor1': '벨기에',
      'year': '2025.01'},
     {'balPayments': '-2190587907',
      'expCnt': '3714',
      'expDlr': '291910343',
      'impCnt': '468',
      'impDlr': '2482498250',
      'statCd': 'SA',
      'statCdCntnKor1': '사우디아라비아',
      'year': '2025.01'},
     {'balPayments': '202929035',
      'expCnt': '2422',
      'expDlr': '281161290',
      'impCnt': '3582',
      'impDlr': '78232255',
      'statCd': 'CZ',
      'statCdCntnKor1': '체코공화국',
      'year': '2025.01'},
     {'balPayments': '197989809',
      'expCnt': '1825',
      'expDlr': '254477023',
      'impCnt': '1155',
      'impDlr': '56487214',
      'statCd': 'HU',
      'statCdCntnKor1': '헝가리',
      'year': '2025.01'},
     {'balPayments': '115537352',
      'expCnt': '1309',
      'expDlr': '253412744',
      'impCnt': '1756',
      'impDlr': '137875392',
      'statCd': 'DK',
      'statCdCntnKor1': '덴마크',
      'year': '2025.01'},
     {'balPayments': '16405506',
      'expCnt': '3984',
      'expDlr': '242347682',
      'impCnt': '9360',
      'impDlr': '225942176',
      'statCd': 'ES',
      'statCdCntnKor1': '스페인',
      'year': '2025.01'},
     {'balPayments': '-278687779',
      'expCnt': '4709',
      'expDlr': '223133772',
      'impCnt': '1140',
      'impDlr': '501821551',
      'statCd': 'RU',
      'statCdCntnKor1': '러시아 연방',
      'year': '2025.01'},
     {'balPayments': '181778535',
      'expCnt': '3714',
      'expDlr': '194103721',
      'impCnt': '50',
      'impDlr': '12325186',
      'statCd': 'KZ',
      'statCdCntnKor1': '카자흐스탄',
      'year': '2025.01'},
     {'balPayments': '164210666',
      'expCnt': '195',
      'expDlr': '181194201',
      'impCnt': '116',
      'impDlr': '16983535',
      'statCd': 'MT',
      'statCdCntnKor1': '몰타',
      'year': '2025.01'},
     {'balPayments': '38972537',
      'expCnt': '3065',
      'expDlr': '175268137',
      'impCnt': '1508',
      'impDlr': '136295600',
      'statCd': 'IL',
      'statCdCntnKor1': '이스라엘',
      'year': '2025.01'},
     {'balPayments': '115530846',
      'expCnt': '1506',
      'expDlr': '170924255',
      'impCnt': '1136',
      'impDlr': '55393409',
      'statCd': 'SK',
      'statCdCntnKor1': '슬로바키아',
      'year': '2025.01'},
     {'balPayments': '37203070',
      'expCnt': '2848',
      'expDlr': '139315474',
      'impCnt': '31775',
      'impDlr': '102112404',
      'statCd': 'NZ',
      'statCdCntnKor1': '뉴질랜드',
      'year': '2025.01'},
     {'balPayments': '-242289202',
      'expCnt': '2119',
      'expDlr': '123920256',
      'impCnt': '1456',
      'impDlr': '366209458',
      'statCd': 'CL',
      'statCdCntnKor1': '칠레',
      'year': '2025.01'},
     {'balPayments': '113257896',
      'expCnt': '5567',
      'expDlr': '114483826',
      'impCnt': '11',
      'impDlr': '1225930',
      'statCd': 'KG',
      'statCdCntnKor1': '키르기스스탄',
      'year': '2025.01'},
     {'balPayments': '113267176',
      'expCnt': '40',
      'expDlr': '113267669',
      'impCnt': '1',
      'impDlr': '493',
      'statCd': 'BS',
      'statCdCntnKor1': '바하마',
      'year': '2025.01'},
     {'balPayments': '108925454',
      'expCnt': '1455',
      'expDlr': '110091202',
      'impCnt': '61',
      'impDlr': '1165748',
      'statCd': 'UZ',
      'statCdCntnKor1': '우즈베키스탄',
      'year': '2025.01'},
     {'balPayments': '68914893',
      'expCnt': '1484',
      'expDlr': '107100732',
      'impCnt': '571',
      'impDlr': '38185839',
      'statCd': 'PK',
      'statCdCntnKor1': '파키스탄',
      'year': '2025.01'},
     {'balPayments': '-178871813',
      'expCnt': '2147',
      'expDlr': '101420663',
      'impCnt': '3507',
      'impDlr': '280292476',
      'statCd': 'CH',
      'statCdCntnKor1': '스위스',
      'year': '2025.01'},
     {'balPayments': '-692454901',
      'expCnt': '733',
      'expDlr': '99544684',
      'impCnt': '80',
      'impDlr': '791999585',
      'statCd': 'IQ',
      'statCdCntnKor1': '이라크',
      'year': '2025.01'},
     {'balPayments': '47008130',
      'expCnt': '2319',
      'expDlr': '99099948',
      'impCnt': '1501',
      'impDlr': '52091818',
      'statCd': 'BD',
      'statCdCntnKor1': '방글라데시',
      'year': '2025.01'},
     {'balPayments': '-59371249',
      'expCnt': '1436',
      'expDlr': '96082640',
      'impCnt': '2789',
      'impDlr': '155453889',
      'statCd': 'SE',
      'statCdCntnKor1': '스웨덴',
      'year': '2025.01'},
     {'balPayments': '85587284',
      'expCnt': '2228',
      'expDlr': '91577613',
      'impCnt': '270',
      'impDlr': '5990329',
      'statCd': 'EG',
      'statCdCntnKor1': '이집트',
      'year': '2025.01'},
     {'balPayments': '78289073',
      'expCnt': '97',
      'expDlr': '78319777',
      'impCnt': '2',
      'impDlr': '30704',
      'statCd': 'AO',
      'statCdCntnKor1': '앙골라',
      'year': '2025.01'},
     {'balPayments': '75017695',
      'expCnt': '899',
      'expDlr': '77923646',
      'impCnt': '78',
      'impDlr': '2905951',
      'statCd': 'PA',
      'statCdCntnKor1': '파나마',
      'year': '2025.01'},
     {'balPayments': '-30206160',
      'expCnt': '914',
      'expDlr': '76335641',
      'impCnt': '975',
      'impDlr': '106541801',
      'statCd': 'IE',
      'statCdCntnKor1': '아일랜드',
      'year': '2025.01'},
     {'balPayments': '-1341160952',
      'expCnt': '908',
      'expDlr': '73034059',
      'impCnt': '200',
      'impDlr': '1414195011',
      'statCd': 'QA',
      'statCdCntnKor1': '카타르',
      'year': '2025.01'},
     {'balPayments': '-29078604',
      'expCnt': '1228',
      'expDlr': '66485795',
      'impCnt': '1158',
      'impDlr': '95564399',
      'statCd': 'CO',
      'statCdCntnKor1': '콜롬비아',
      'year': '2025.01'},
     {'balPayments': '-434507048',
      'expCnt': '993',
      'expDlr': '65013103',
      'impCnt': '60',
      'impDlr': '499520151',
      'statCd': 'OM',
      'statCdCntnKor1': '오만',
      'year': '2025.01'},
     {'balPayments': '57423629',
      'expCnt': '637',
      'expDlr': '63883078',
      'impCnt': '294',
      'impDlr': '6459449',
      'statCd': 'SI',
      'statCdCntnKor1': '슬로베니아',
      'year': '2025.01'},
     {'balPayments': '-50904417',
      'expCnt': '2179',
      'expDlr': '62081514',
      'impCnt': '1611',
      'impDlr': '112985931',
      'statCd': 'AT',
      'statCdCntnKor1': '오스트리아',
      'year': '2025.01'},
     {'balPayments': '57810611',
      'expCnt': '122',
      'expDlr': '58354480',
      'impCnt': '22',
      'impDlr': '543869',
      'statCd': 'PY',
      'statCdCntnKor1': '파라과이',
      'year': '2025.01'},
     {'balPayments': '19665344',
      'expCnt': '1011',
      'expDlr': '56927732',
      'impCnt': '4249',
      'impDlr': '37262388',
      'statCd': 'PT',
      'statCdCntnKor1': '포루투갈',
      'year': '2025.01'},
     {'balPayments': '51030086',
      'expCnt': '2013',
      'expDlr': '55723382',
      'impCnt': '100',
      'impDlr': '4693296',
      'statCd': 'JO',
      'statCdCntnKor1': '요르단',
      'year': '2025.01'},
     {'balPayments': '7615156',
      'expCnt': '1812',
      'expDlr': '49598669',
      'impCnt': '1020',
      'impDlr': '41983513',
      'statCd': 'KH',
      'statCdCntnKor1': '캄보디아',
      'year': '2025.01'},
     {'balPayments': '-28983653',
      'expCnt': '749',
      'expDlr': '45115522',
      'impCnt': '1038',
      'impDlr': '74099175',
      'statCd': 'FI',
      'statCdCntnKor1': '핀란드',
      'year': '2025.01'},
     {'balPayments': '43008622',
      'expCnt': '535',
      'expDlr': '43488239',
      'impCnt': '49',
      'impDlr': '479617',
      'statCd': 'GU',
      'statCdCntnKor1': '괌',
      'year': '2025.01'},
     {'balPayments': '-6191048',
      'expCnt': '1059',
      'expDlr': '41323267',
      'impCnt': '3403',
      'impDlr': '47514315',
      'statCd': 'RO',
      'statCdCntnKor1': '루마니아',
      'year': '2025.01'},
     {'balPayments': '-38862218',
      'expCnt': '851',
      'expDlr': '41085566',
      'impCnt': '54',
      'impDlr': '79947784',
      'statCd': 'NG',
      'statCdCntnKor1': '나이지리아',
      'year': '2025.01'},
     {'balPayments': '-217157991',
      'expCnt': '1146',
      'expDlr': '40437898',
      'impCnt': '791',
      'impDlr': '257595889',
      'statCd': 'PE',
      'statCdCntnKor1': '페루',
      'year': '2025.01'},
     {'balPayments': '-223443714',
      'expCnt': '1406',
      'expDlr': '39934581',
      'impCnt': '310',
      'impDlr': '263378295',
      'statCd': 'ZA',
      'statCdCntnKor1': '남아프리카공화국',
      'year': '2025.01'},
     {'balPayments': '-766568709',
      'expCnt': '699',
      'expDlr': '35753099',
      'impCnt': '64',
      'impDlr': '802321808',
      'statCd': 'KW',
      'statCdCntnKor1': '쿠웨이트',
      'year': '2025.01'},
     {'balPayments': '-89320728',
      'expCnt': '772',
      'expDlr': '34938711',
      'impCnt': '1928',
      'impDlr': '124259439',
      'statCd': 'NO',
      'statCdCntnKor1': '노르웨이',
      'year': '2025.01'},
     {'balPayments': '23013568',
      'expCnt': '364',
      'expDlr': '34893762',
      'impCnt': '116',
      'impDlr': '11880194',
      'statCd': 'PR',
      'statCdCntnKor1': '푸에르토리코',
      'year': '2025.01'},
     {'balPayments': '1398927',
      'expCnt': '775',
      'expDlr': '33059806',
      'impCnt': '167',
      'impDlr': '31660879',
      'statCd': 'UA',
      'statCdCntnKor1': '우크라이나',
      'year': '2025.01'},
     {'balPayments': '30026549',
      'expCnt': '9568',
      'expDlr': '31688929',
      'impCnt': '16',
      'impDlr': '1662380',
      'statCd': 'LY',
      'statCdCntnKor1': '리비아',
      'year': '2025.01'},
     {'balPayments': '28968176',
      'expCnt': '2280',
      'expDlr': '31639167',
      'impCnt': '1311',
      'impDlr': '2670991',
      'statCd': 'MN',
      'statCdCntnKor1': '몽골',
      'year': '2025.01'},
     {'balPayments': '4868584',
      'expCnt': '192',
      'expDlr': '29884981',
      'impCnt': '217',
      'impDlr': '25016397',
      'statCd': 'LA',
      'statCdCntnKor1': '라오스',
      'year': '2025.01'},
     {'balPayments': '23072319',
      'expCnt': '413',
      'expDlr': '29687011',
      'impCnt': '480',
      'impDlr': '6614692',
      'statCd': 'LT',
      'statCdCntnKor1': '리투아니아',
      'year': '2025.01'},
     {'balPayments': '-66463918',
      'expCnt': '994',
      'expDlr': '27196412',
      'impCnt': '382',
      'impDlr': '93660330',
      'statCd': 'GR',
      'statCdCntnKor1': '그리스',
      'year': '2025.01'},
     {'balPayments': '-94682645',
      'expCnt': '766',
      'expDlr': '27035269',
      'impCnt': '364',
      'impDlr': '121717914',
      'statCd': 'AR',
      'statCdCntnKor1': '아르헨티나',
      'year': '2025.01'},
     {'balPayments': '-18552676',
      'expCnt': '776',
      'expDlr': '23365844',
      'impCnt': '2256',
      'impDlr': '41918520',
      'statCd': 'MM',
      'statCdCntnKor1': '미얀마',
      'year': '2025.01'},
     {'balPayments': '17643008',
      'expCnt': '187',
      'expDlr': '21022855',
      'impCnt': '97',
      'impDlr': '3379847',
      'statCd': 'SV',
      'statCdCntnKor1': '엘살바도르',
      'year': '2025.01'},
     {'balPayments': '7589727',
      'expCnt': '376',
      'expDlr': '20647032',
      'impCnt': '360',
      'impDlr': '13057305',
      'statCd': 'MA',
      'statCdCntnKor1': '모로코',
      'year': '2025.01'},
     {'balPayments': '8820066',
      'expCnt': '363',
      'expDlr': '20629980',
      'impCnt': '207',
      'impDlr': '11809914',
      'statCd': 'EC',
      'statCdCntnKor1': '에쿠아도르',
      'year': '2025.01'},
     {'balPayments': '-435176545',
      'expCnt': '247',
      'expDlr': '20215696',
      'impCnt': '28',
      'impDlr': '455392241',
      'statCd': 'DZ',
      'statCdCntnKor1': '알제리',
      'year': '2025.01'},
     {'balPayments': '10991759',
      'expCnt': '729',
      'expDlr': '18323773',
      'impCnt': '182',
      'impDlr': '7332014',
      'statCd': 'GT',
      'statCdCntnKor1': '과테말라',
      'year': '2025.01'},
     {'balPayments': '9423445',
      'expCnt': '475',
      'expDlr': '18160181',
      'impCnt': '122',
      'impDlr': '8736736',
      'statCd': 'DO',
      'statCdCntnKor1': '도미니카 공화국',
      'year': '2025.01'},
     {'balPayments': '10625624',
      'expCnt': '746',
      'expDlr': '17112799',
      'impCnt': '22',
      'impDlr': '6487175',
      'statCd': 'GH',
      'statCdCntnKor1': '가나',
      'year': '2025.01'},
     {'balPayments': '6817335',
      'expCnt': '700',
      'expDlr': '16795993',
      'impCnt': '461',
      'impDlr': '9978658',
      'statCd': 'LK',
      'statCdCntnKor1': '스리랑카',
      'year': '2025.01'},
     {'balPayments': '15873345',
      'expCnt': '2307',
      'expDlr': '15873345',
      'impCnt': '0',
      'impDlr': '0',
      'statCd': 'TJ',
      'statCdCntnKor1': '타지크',
      'year': '2025.01'},
     {'balPayments': '14045408',
      'expCnt': '1112',
      'expDlr': '14910996',
      'impCnt': '79',
      'impDlr': '865588',
      'statCd': 'AL',
      'statCdCntnKor1': '알바니아',
      'year': '2025.01'},
     {'balPayments': '4348288',
      'expCnt': '856',
      'expDlr': '13469713',
      'impCnt': '363',
      'impDlr': '9121425',
      'statCd': 'CR',
      'statCdCntnKor1': '코스타리카',
      'year': '2025.01'},
     {'balPayments': '-12843206',
      'expCnt': '458',
      'expDlr': '12897979',
      'impCnt': '842',
      'impDlr': '25741185',
      'statCd': 'BG',
      'statCdCntnKor1': '불가리아',
      'year': '2025.01'},
     {'balPayments': '10744398',
      'expCnt': '23',
      'expDlr': '12106161',
      'impCnt': '15',
      'impDlr': '1361763',
      'statCd': 'SL',
      'statCdCntnKor1': '시에라 리온',
      'year': '2025.01'},
     {'balPayments': '9771645',
      'expCnt': '373',
      'expDlr': '11511870',
      'impCnt': '74',
      'impDlr': '1740225',
      'statCd': 'HN',
      'statCdCntnKor1': '온두라스',
      'year': '2025.01'},
     {'balPayments': '3226289',
      'expCnt': '302',
      'expDlr': '11466446',
      'impCnt': '31',

In [ ]:
# 원하는 데이터 추출
# 이 경로는 API 응답 데이터의 구조에 따라 달르므로, API 문서 참고해 키를 확인해야 됨.
result = xml_dict['response']['body']['items']['item']

# 딕셔너리를 데이터프레임으로 변환
im_export = pd.json_normalize(result)
im_export.head()

,balPayments,expCnt,expDlr,impCnt,impDlr,statCd,statCdCntnKor1,year
0,3443225952,193178,9282566788,1416582,5839340836,US,미국,2025.01
1,-2004621045,91388,9204172269,1225173,11208793314,CN,중국,2025.01
2,1792245180,57209,4356972160,145132,2564726980,VN,베트남,2025.01
3,210300569,34078,2438188048,20022,2227887479,TW,대만,2025.01
4,-1223548429,146929,2363796881,344783,3587345310,JP,일본,2025.01

**데이터셋 설명**

- balPayments: 무역수지(달러)
- expCnt: 수출건수
- expDlr: 수출금액(달러)
- impCnt: 수입건수
- impDlr: 수입금액(달러)
- statCd: 국가코드
- statCdCntnKor1: 국가
- year: 기간

### 1.1.2.데이터 분석

- Pandas는 숫자가 크면 숫자를 2.805000e+03 형태로 표시한다.
- 가독성을 높이기 위해 이후 숫자 출력은 소수점 두자리를 갖는 일반 형태로 표시하게 한다.

In [ ]:
# 소수점 네 자리까지 표시
pd.set_option('display.float_format', lambda x: '%.2f' % x)

**1) 데이터 탐색 및 전처리**

- 열 이름, 데이터 형식 등 열 정보 확인

In [ ]:
im_export.info()

<class 'pandas.DataFrame'>
RangeIndex: 2830 entries, 0 to 2829
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   balPayments     2830 non-null   str
 1   expCnt          2830 non-null   str
 2   expDlr          2830 non-null   str
 3   impCnt          2830 non-null   str
 4   impDlr          2830 non-null   str
 5   statCd          2830 non-null   str
 6   statCdCntnKor1  2830 non-null   str
 7   year            2830 non-null   str
dtypes: str(8)
memory usage: 177.0 KB

- 이후 수치 비교를 위해 숫자 데이터를 int64로 변환
- 대상 열: balPayments, expCnt, expDlr, impCnt, impDlr
- 구문 예) df['Money'].astype('int64')

In [ ]:
cols = ['balPayments', 'expCnt', 'expDlr', 'impCnt', 'impDlr']
im_export[cols] = im_export[cols].astype('int64')
im_export.info()

<class 'pandas.DataFrame'>
RangeIndex: 2830 entries, 0 to 2829
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   balPayments     2830 non-null   int64
 1   expCnt          2830 non-null   int64
 2   expDlr          2830 non-null   int64
 3   impCnt          2830 non-null   int64
 4   impDlr          2830 non-null   int64
 5   statCd          2830 non-null   str
 6   statCdCntnKor1  2830 non-null   str
 7   year            2830 non-null   str
dtypes: int64(5), str(3)
memory usage: 177.0 KB

In [ ]:
# 기초통계정보
im_export.describe()

         balPayments    expCnt         expDlr     impCnt         impDlr
count        2830.00   2830.00        2830.00    2830.00        2830.00
mean     27362076.73   4870.13   250646658.94   19270.59   223284582.21
std     477349207.86  23761.40  1105703183.57  145392.20   978743396.01
min   -2459852528.00      0.00           0.00       0.00           0.00
25%       -209850.25     16.25      556300.00       2.00       10265.75
50%        566795.50    141.00     5100655.00      21.00     1331979.50
75%       9670287.50   1117.75    56715844.00     373.75    46289235.50
max    5717645732.00 459337.00 12964960895.00 1945296.00 13729115193.00

**2) 2025년 12월 무역수지 TOP 10**

- 2025년 12월 데이터를 별도로 추출하여 **im_export12** 데이터프레임을 만듭니다.
- 무역수지(balPayments)를 기준으로 내림차순 정렬합니다.
- 정렬 결과로 어긋난 순서의 인덱스를 깔끔하게 초기화합니다.
- 상위 10개 행만 출력해 2025년 12월 무역수지 TOP 10을 확인합니다.

In [ ]:
im_export12 = im_export.loc[im_export['year']=='2025.12']
im_export12 = im_export12.sort_values(by='balPayments', ascending=False)
im_export12.reset_index(drop=True, inplace=True)

im_export12.head(10)

,balPayments,expCnt,expDlr,impCnt,impDlr,statCd,statCdCntnKor1,year
0,5561530992,232653,12335136415,1267690,6773605423,US,미국,2025.12
1,4280632585,38739,4624113700,391772,343481115,HK,홍콩,2025.12
2,3332483885,67807,6281464305,233578,2948980420,VN,베트남,2025.12
3,2256773042,68113,5131207266,25051,2874434224,TW,대만,2025.12
4,1200481846,21241,1719209860,13877,518728014,IN,인도,2025.12
5,1033101128,54471,2069320523,16861,1036219395,SG,싱가포르,2025.12
6,1008638544,43,1008679079,12,40535,MH,마샬군도,2025.12
7,896992758,33414,1203925892,6328,306933134,PH,필리핀,2025.12
8,594935421,6918,744839034,3206,149903613,TR,튀르키예,2025.12
9,439455893,16482,1050832758,8690,611376865,MX,멕시코,2025.12