# [실습] 단변량 분석

# 1.비즈니스 시나리오


- 고객사는 카시트 전문 판매 회사입니다.
    - 최근, 매출 그래프가 조금씩 아래로 향하기 시작했습니다. 회사의 여러 부서에서는 다양한 원인을 제시했지만, 그 원인들이 정말 데이터에 기반한 것인지는 여전히 의문입니다.

    - 부서별 문제 진단:
        - 가격 경쟁력 약화: 경쟁사와의 가격 경쟁에서 밀리고 있음
        - 광고비 집행 비효율: 광고비는 쓰고 있지만, 정말 적절하게 집행되지 않음
        - 국내 시장 편중: 해외 시장 개척은 뒷전이고, 국내 시장에만 집중됨
        - 지역 구매력 미파악: 지역별 구매력과 특성을 제대로 분석하지 못하고 있음

- 이 문제를 해결하기 위해 DX 프로젝트 팀이 빌딩되었습니다.
    - 여러분은 이 팀에서 데이터 분석을 책임지는 DX 컨설턴트로 합류했습니다.
    - 드디어 갈고 닦은 실력을 발휘할 기회가 주어졌습니다.
    - 자, 이제 단변량 분석을 통해 비즈니스 인사이트를 도출해 봅시다!
----
* 반복되는 코드는 함수로 만듭시다!
    * 함수를 만드는 순서
        * 먼저 절차대로 코드를 작성해서 실행한다.
        * 실행된 코드(오류가 없는 코드)를 가져다 함수로 구성한다.
            * 입력과 출력 결정

# 2.환경준비

## 2.1. 라이브러리 불러오기

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## 2.2. 데이터 불러오기 : 카시트 판매량 데이터

|	변수명	|	설명	|	구분	|
|	----	|	----	|	----	|
|	Sales 	|	 각 지역 판매량(단위 : 1000개)	|	Target	|
|	CompPrice 	|	 경쟁사 가격(단위 : 달러)	|	feature	|
|	Income 	|	 지역 평균 소득(단위 : 1000달러)	|	feature	|
|	Advertising 	|	 각 지역, 회사의 광고 예산(단위 : 1000달러)	|	feature	|
|	Population 	|	 지역 인구수(단위 : 1000명)	|	feature	|
|	Price 	|	 자사 지역별 판매가격	|	feature	|
|	ShelveLoc 	|	 진열상태	|	feature	|
|	Age 	|	 지역 인구의 평균 연령	|	feature	|
|	Urban 	|	 도심 지역 여부(Yes,No)	|	feature	|
|	US 	|	 매장이 미국에 있는지 여부(Yes,No)	|	feature	|

In [2]:
path = './data/Carseats.csv'

car = pd.read_csv(path)

car.head()

,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Urban,US
0,9.50,138,73,11,276,120,Bad,42,Yes,Yes
1,11.22,111,48,16,260,83,Good,65,Yes,Yes
2,10.06,113,35,10,269,80,Medium,59,Yes,Yes
3,7.40,117,100,4,466,97,Medium,55,Yes,Yes
4,4.15,141,64,3,340,128,Bad,38,Yes,No

In [3]:
car.describe()

,Sales,CompPrice,Income,Advertising,Population,Price,Age
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,7.496325,124.975000,68.657500,6.635000,264.840000,115.795000,53.322500
std,2.824115,15.334512,27.986037,6.650364,147.376436,23.676664,16.200297
min,0.000000,77.000000,21.000000,0.000000,10.000000,24.000000,25.000000
25%,5.390000,115.000000,42.750000,0.000000,139.000000,100.000000,39.750000
50%,7.490000,125.000000,69.000000,5.000000,272.000000,117.000000,54.500000
75%,9.320000,135.000000,91.000000,12.000000,398.500000,131.000000,66.000000
max,16.270000,175.000000,120.000000,29.000000,509.000000,191.000000,80.000000

In [4]:
car.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Sales        400 non-null    float64
 1   CompPrice    400 non-null    int64
 2   Income       400 non-null    int64
 3   Advertising  400 non-null    int64
 4   Population   400 non-null    int64
 5   Price        400 non-null    int64
 6   ShelveLoc    400 non-null    str
 7   Age          400 non-null    int64
 8   Urban        400 non-null    str
 9   US           400 non-null    str
dtypes: float64(1), int64(6), str(3)
memory usage: 31.4 KB

# 3.단변량 분석 : 숫자형 변수

## 3.1. Sales (Target)

1) 변수의 비즈니스 의미

* 각 지역 판매량(단위 : 1000개)
* Target

2) 기초통계량(수치화)

3) 분포 확인(시각화)

4) 기초통계량과 분포를 통해서 파악한 내용을 적어 봅시다.

보이는 그대로를 넘어, 비즈니스 관점에서 고민하며 적어 봅시다.

5) 추가 분석해 볼 사항이 있나요?

## 3.2. CompPrice

1) 변수의 비즈니스 의미

- 경쟁사 가격(단위:달러)

2) 기초통계량(수치화)

3) 분포 확인(시각화)

4) 기초통계량과 분포를 통해서 파악한 내용을 적어 봅시다.

보이는 그대로를 넘어, 비즈니스 관점에서 고민하며 적어 봅시다.

5) 추가 분석해 볼 사항이 있나요?

## 3.3. Income

1) 변수의 비즈니스 의미

- 지역 평균 소득(단위: 1000달러)

2) 기초통계량(수치화)

3) 분포 확인(시각화)

4) 기초통계량과 분포를 통해서 파악한 내용을 적어 봅시다.

보이는 그대로를 넘어, 비즈니스 관점에서 고민하며 적어 봅시다.

5) 추가 분석해 볼 사항이 있나요?

## 3.4. Advertising

1) 변수의 비즈니스 의미

- 각 지역, 회사의 광고 예산(단위:1000달러)

2) 기초통계량(수치화)

3) 분포 확인(시각화)

4) 기초통계량과 분포를 통해서 파악한 내용을 적어 봅시다.

보이는 그대로를 넘어, 비즈니스 관점에서 고민하며 적어 봅시다.

5) 추가 분석해 볼 사항이 있나요?

## 3.5. Population

1) 변수의 비즈니스 의미

- 지역 인구수(단위:1000명)

2) 기초통계량(수치화)

3) 분포 확인(시각화)

4) 기초통계량과 분포를 통해서 파악한 내용을 적어 봅시다.

보이는 그대로를 넘어, 비즈니스 관점에서 고민하며 적어 봅시다.

5) 추가 분석해 볼 사항이 있나요?

## 3.6. Price

1) 변수의 비즈니스 의미

- 자사 지역별 판매가격

2) 기초통계량(수치화)

3) 분포 확인(시각화)

4) 기초통계량과 분포를 통해서 파악한 내용을 적어 봅시다.

보이는 그대로를 넘어, 비즈니스 관점에서 고민하며 적어 봅시다.

5) 추가 분석해 볼 사항이 있나요?

(추가) Price vs CompPrice

## 3.7. Age

1) 변수의 비즈니스 의미

- 지역 인구의 평균 연령

2) 기초통계량(수치화)

3) 분포 확인(시각화)

4) 기초통계량과 분포를 통해서 파악한 내용을 적어 봅시다.

보이는 그대로를 넘어, 비즈니스 관점에서 고민하며 적어 봅시다.

5) 추가 분석해 볼 사항이 있나요?

# 4.단변량 분석 : 범주형 변수

## 4.1. Urban

1) 변수의 비즈니스 의미

- 도심 지역 여부(Yes, No)

2) 기초통계량(수치화)

3) 분포 확인(시각화)

4) 기초통계량과 분포를 통해서 파악한 내용을 적어 봅시다.

보이는 그대로를 넘어, 비즈니스 관점에서 고민하며 적어 봅시다.

5) 추가 분석해 볼 사항이 있나요?

## 4.2. ShelveLoc

1) 변수의 비즈니스 의미

* 매장 진열상태

2) 기초통계량(수치화)

3) 분포 확인(시각화)

4) 기초통계량과 분포를 통해서 파악한 내용을 적어 봅시다.

보이는 그대로를 넘어, 비즈니스 관점에서 고민하며 적어 봅시다.

5) 추가 분석해 볼 사항이 있나요?

## 4.3. US

1) 변수의 비즈니스 의미

- 매장이 미국에 있는지 여부(Yes, No)

2) 기초통계량(수치화)

3) 분포 확인(시각화)

4) 기초통계량과 분포를 통해서 파악한 내용을 적어 봅시다.

보이는 그대로를 넘어, 비즈니스 관점에서 고민하며 적어 봅시다.

5) 추가 분석해 볼 사항이 있나요?