# 1.환경 준비

In [1]:
# 라이브러리 불러오기
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings(action='ignore')
%config InlineBackend.figure_format = 'retina'

In [2]:
# 데이터 불러오기
path = './dataset/attrition.csv'
df = pd.read_csv(path)

# 2.데이터 이해

In [3]:
# 데이터 살펴보기
df.head()

,Attrition,Age,DistanceFromHome,EmployeeNumber,Gender,JobSatisfaction,MaritalStatus,MonthlyIncome,OverTime,PercentSalaryHike,TotalWorkingYears
0,0,33,7,817,Male,3,Married,11691,No,11,14
1,0,35,18,1412,Male,4,Single,9362,No,11,10
2,0,42,6,1911,Male,1,Married,13348,No,13,18
3,0,46,2,1204,Female,1,Married,17048,No,23,28
4,1,22,4,593,Male,3,Single,3894,No,16,4

**데이터 설명**

- Attrition: 이직 여부 (1: 이직, 0: 잔류)
- Age: 나이
- DistanceFromHome: 집-직장 거리 (단위: 마일)
- EmployeeNumber: 사번
- Gender: 성별 (Male, Female)
- JobSatisfaction: 직무 만족도(1: Low, 2: Medium, 3: High, 4: Very High)
- MaritalStatus: 결혼 상태 (Single, Married, Divorced)
- MonthlyIncome: 월급 (단위: 달러)
- OverTime: 야근 여부 (Yes, No)
- PercentSalaryHike: 전년 대비 급여 인상율(단위: %)
- TotalWorkingYears: 총 경력 연수

In [4]:
# 기술통계 확인
df.describe()

,Attrition,Age,DistanceFromHome,EmployeeNumber,JobSatisfaction,MonthlyIncome,PercentSalaryHike,TotalWorkingYears
count,1196.000000,1196.00000,1196.000000,1196.000000,1196.000000,1196.000000,1196.000000,1196.000000
mean,0.163043,36.94398,9.258361,1035.629599,2.716555,6520.104515,15.251672,11.330268
std,0.369560,9.09270,8.166016,604.340130,1.110962,4665.902253,3.625946,7.823821
min,0.000000,18.00000,1.000000,1.000000,1.000000,1009.000000,11.000000,0.000000
25%,0.000000,30.00000,2.000000,507.750000,2.000000,2928.250000,12.000000,6.000000
50%,0.000000,36.00000,7.000000,1028.000000,3.000000,4973.500000,14.000000,10.000000
75%,0.000000,43.00000,14.000000,1581.250000,4.000000,8420.500000,18.000000,15.000000
max,1.000000,60.00000,29.000000,2068.000000,4.000000,19999.000000,25.000000,40.000000

# 3.데이터 전처리

**1) 변수 제거**

- 제거 대상 변수: EmployeeNumber

In [ ]:
# 제거 대상: EmployeeNumber
del_cols = ['EmployeeNumber']


# 변수 제거




# 확인

**2) x, y 분리**

In [ ]:
# target 확인


# 데이터 분리

**3) 가변수화**

In [ ]:
# 가변수화 대상: Gender, JobSatisfaction, MaritalStatus, OverTime


# 가변수화


# 확인

**4) 학습용, 평가용 데이터 분리**

In [ ]:
# 모듈 불러오기


# 데이터 분리

**5) 정규화**

In [ ]:
# 모듈 불러오기


# 정규화

# 4.성능 예측

- 여러 알고리즘으로 모델을 만들고 K-Fold CV로 성능을 예측한다.
- 하이퍼파라미터를 설정하지 않고 진행한다.
- 각 모델의 성능 정보를 수집해 마지막에 비교한다.

In [ ]:
# xgboost 설치
# pip install xgboost

In [ ]:
# lightgbm 설치
# pip install lightgbm

- 이후 사용할 함수를 모두 불러옵니다.

In [ ]:
# 불러오기

**1) KNN**

- KNN 알고리즘으로 모델링하고 K-Fold CV로 성능 검증

In [ ]:
# 선언하기

In [ ]:
# 성능예측

In [ ]:
# 결과확인

In [ ]:
# 결과수집

**2) Decision Tree**

- Decision Tree 알고리즘으로 모델링하고 K-Fold CV로 성능 검증

In [ ]:
# 선언하기

In [ ]:
# 성능예측

In [ ]:
# 결과확인

In [ ]:
# 결과수집

**3) Logistic Regression**

- Logistic Regression 알고리즘으로 모델링하고 K-Fold CV로 성능 검증

In [ ]:
# 선언하기

In [ ]:
# 성능예측

In [ ]:
# 결과확인

In [ ]:
# 결과수집

**4) SVM**

- SVM 알고리즘으로 모델링하고 K-Fold CV로 성능 검증

In [ ]:
# 선언하기

In [ ]:
# 성능예측

In [ ]:
# 결과확인

In [ ]:
# 결과수집

**5) Random Forest**

- Random Forest 알고리즘으로 모델링하고 K-Fold CV로 성능 검증

In [ ]:
# 선언하기

In [ ]:
# 성능예측

In [ ]:
# 결과확인

In [ ]:
# 결과수집

**6) XGBoost**

- XGBoost 알고리즘으로 모델링하고 K-Fold CV로 성능 검증

In [ ]:
# 선언하기

In [ ]:
# 성능예측

In [ ]:
# 결과확인

In [ ]:
# 결과수집

**7) LightGBM**

- LightGBM 알고리즘으로 모델링하고 K-Fold CV로 성능 검증

In [ ]:
# 선언하기

In [ ]:
# 성능예측

In [ ]:
# 결과확인

In [ ]:
# 결과수집

# 5.결과 확인

- 예측된 각 모델의 성능 비교

In [ ]:
# 성능 비교

In [ ]:
# 성능 시각화 비교

# 6.성능 튜닝

- 위에서 성능이 가장 좋을 것으로 예측된 모델 튜닝

In [ ]:
# 기본 모델 선언


# 파라미터 지정



# 모델 선언

In [ ]:
# 학습하기(많은 시간이 소요될 수 있음)

In [ ]:
# 최적 파라미터, 예측 최고 성능

In [ ]:
# 변수 중요도 시각화

# 7.성능 평가

- 최적 파라미터로 학습된 모델에 대해 최종 성능 평가 진행

In [ ]:
# 예측하기

In [ ]:
# 성능평가